### ISSUE TITLE
[Request] search plugin for https://www.torrentdownloads.me

### ISSUE THREAD

**Issue by StephenJau** [qbittorrent/search-plugins#10]
Could you please write a search plugin for https://www.torrentdownloads.me please ?.
This site considered a good site. Asking for a favor for a plugin.py file. Manythx

**Comment by Pireo** [comment]
https://github.com/lima66/Torrents_Plugin/blob/master/torrentdownloads.py

**Comment by Shachar2like** [comment]
says that the plug in is unsupported. (read something in the how to section to make two filenames the same)

**Comment by Chocobo1** [comment]
>https://github.com/lima66/Torrents_Plugin/blob/master/torrentdownloads.py

@lima66
You mind adding an entry in the wiki?
https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins
