### ISSUE TITLE
RARBG plugin not returning any results

### ISSUE THREAD

**Issue by isavcic** [qbittorrent/search-plugins#101]
Hello, I've noticed that RARBG plugin doesn't return any results.

I ran it manually as well:
```
..\nova2.py rarbg all 720p
```

**Comment by ngosang** [comment]
It's working for me. What is your python version?

**Comment by isavcic** [comment]
Windows 7 64-bit, Python 3.7.3 64-bit, I've tested under Linux and strangely it works. I've confirmed that this version of Python is used when search is performed.

**Comment by b0nk** [comment]
check the script version on nova and nova3 folders on both your machines. compare it with the repo version.
It also works on my end on Win8 and Linux python3
can't really understand what  it could be

**Comment by isavcic** [comment]
I've nuked the nova and nova3 dirs from my AppData, let qBitTorrent recreate them, populated them with the plugins from the repo, to no avail. Troubleshooting these plugins is a pain, can you please provide me with some instructions and/or hints on how to troubleshoot, as your "works for me" won't make it miraculously work on my machine as well.

**Comment by isavcic** [comment]
Is this plugin incompatible with Python 3.7? On a freshly installed system, wasn't working with 3.7, started working with 3.6.

**Comment by ngosang** [comment]
@isavcic Tested in Python 3.7.4. It's working
