### ISSUE TITLE
Why is the jackett search result slower than the built in plugins?

### ISSUE THREAD

**Issue by laichiaheng** [qbittorrent/search-plugins#103]
It searches much slower than other built in plugins.

**Comment by ngosang** [comment]
Are you talking about Jackett?

**Comment by laichiaheng** [comment]
@ngosang Yes.

**Comment by ngosang** [comment]
@laichiaheng We aren't doing anything special, maybe you have too many trackers configured in Jackett. In the current implementation we are searching using all configured trackers in Jackett. You can try to search in the Jackett UI (all trackers). The response time should be the same.

**Comment by Piccirello** [comment]
I’ve experienced some slowness too but haven’t looked into it any further. I believe jackett has the ability to stream results as they become available. Are we possibly waiting for all results for displaying?

**Comment by ngosang** [comment]
@Piccirello All results come together. The same occurs in the Jacket Web UI.
