### ISSUE TITLE
Search plugins init

### ISSUE THREAD

**Issue by Ilias48rus** [qbittorrent/search-plugins#107]
Its literally nowhere said a single word about using the Check For Updates button to load official plugins .
And the unofficial plugins download links are set to open the files and not to download them, thats just weird .

**Comment by Ilias48rus** [comment]
And where to hell is the Jackett UI that the Jackett API Key should be found at?

**Comment by hdkiller** [comment]
You have to install Jackett for that. 

https://github.com/Jackett/Jackett

Then your-jackett-host:9117/UI/Dashboard You will find the API key there. 

The documentation indeed lacks of the instruction to press the Check For Updates button to fetch the official plugins.

**Comment by ngosang** [comment]
You will find these links useful:
https://github.com/qbittorrent/search-plugins/wiki/Install-search-plugins
https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin
