### ISSUE TITLE
Search pluggins not supported

### ISSUE THREAD

**Issue by paul111111** [qbittorrent/search-plugins#109]
All was good with the search plugins, but just opened qtorrent, search plugins gone and when I try to re install them reinstall via link or local, just keep getting not supported.

**Comment by linuxwwarrior** [comment]
I just opened qbittorrent 4.1.7 in Ubuntu 18.04.2 and the other day all my plugins were there, but now I am having the same issue, all my search plugins are gone and I cant reinstall any, gives incompatible error.  Did anyone resolve this yet??

**Comment by thalieht** [comment]
https://github.com/qbittorrent/qBittorrent/issues/11149#issuecomment-530864855

**Comment by ngosang** [comment]
This bug is related to the Python cache and I can't do anything to fix it.
If you are having the same problem, you will find a fix in https://github.com/qbittorrent/qBittorrent/issues/11149#issuecomment-530864855
Thanks @thalieht

**Comment by paul111111** [comment]
Sorted with fix show above all working now,  thanks
