### ISSUE TITLE
TnT search engine not working

### ISSUE THREAD

**Issue by Tox46** [qbittorrent/search-plugins#110]
The tnt search engine provided is at the moment not working (due to tnt closing in 30/08/19) i'm currently working on a new version of the S.E. which will work through web.archive.com where all pages are listed

**Comment by ngosang** [comment]
@Tox46 TNT Village is unofficial plugin. It was maintained by me but I'm not interested in doing the web archive version. Reopen this issue when you have a working plugin.

Old plugin => https://github.com/ngosang/qBittorrent-plugins
