### ISSUE TITLE
Python GUI on installation the plugin

### ISSUE THREAD

**Issue by imDMG** [qbittorrent/search-plugins#117]
So, i experiment with python gui. And overall everything is fine, but during plugin installation qbittorrent does not wait for the window to close (executing code) and skips installation with compatibility error.

How it fix, if it posible?

Link to code: https://github.com/imDMG/qBt_SE/raw/master/gui_kinozal.py

**Comment by ngosang** [comment]
@imDMG Sobby, but we can't give support for unofficial plugins. You can contact the original author => imdmgg@gmail.com

**Comment by ngosang** [comment]
LOL, I didn't see you are the original author. 
I recommend you to take a look at Jackett plugin source code. We are creating a .json file with the user login.
https://github.com/qbittorrent/search-plugins/blob/master/nova3/engines/jackett.py

**Comment by imDMG** [comment]
I looked at the Jacket, but it has a small issue, the authors abandoned the proxy in favor of vpn. This is the main problem, because of which I returned to the develop of plugins.

**Comment by ngosang** [comment]
I'm not telling you to use Jackett. The main problem with your plugin is that it has external dependencies. These dependencies are not included in python installation:
```
from tkinter import *
from tkinter import messagebox
from tkinter.ttk import *
```
Just remove them and use as few as possible.

**Comment by imDMG** [comment]
I don't understand you, tkinter is a base library of python. Or you talking about something else?

**Comment by ngosang** [comment]
> I don't understand you, tkinter is a base library of python.

I'm using ArchLinux and you have to install it as external dependency. I don't have it installed and your plugin fails for that reason. That's why I recommend you to keep it as simple as possible.

**Comment by imDMG** [comment]
I,m confusing. Maybe you using python 2+, because "Tkinter is Python's de-facto standard GUI" (from wiki).
P.S. in list of plugins i specified the minimum version of python (3.6+)

**Comment by ngosang** [comment]
Python 3
https://coffeecode7.wordpress.com/2017/10/31/installing-tkinter-in-manjaroarch-linux/
https://bbs.archlinux.org/viewtopic.php?id=224553

**Comment by imDMG** [comment]
Ok, now i understood. This library is not full cross OS as specified.
My goal was to install the plugin from one file, without the need to manually add/edit others. Have to give up this idea.
Closing this issue.
