### ISSUE TITLE
the last update on mint 19.2 lost all search plugins

### ISSUE THREAD

**Issue by Tetractys** [qbittorrent/search-plugins#118]
As the title.
![image](https://user-images.githubusercontent.com/465836/68071845-22ead500-fd7f-11e9-8bc5-24d41d4b222e.png)

All try to import plugins from https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins result not compatible.
Any idea?
Thank you in advance.

**Comment by txtsd** [comment]
The [IPTorrents plugin](https://github.com/txtsd/qB-IPT/) I developed is being reported as incompatible too.

**Comment by Tetractys** [comment]
new update this morning (UTC+1):
no way to list the search plugin installed nor "search for update":

![image](https://user-images.githubusercontent.com/465836/68107450-3ca62c80-fee5-11e9-8f5d-506f3322af33.png)

inxi -Fxz:
thor@thor ~ $ inxi -Fxz
System:    Host: thor Kernel: 4.15.0-66-lowlatency x86_64 bits: 64 compiler: gcc v: 7.4.0 Desktop: Cinnamon 4.2.4 
           Distro: Linux Mint 19.2 Tina base: Ubuntu 18.04 bionic 
Machine:   Type: Desktop Mobo: ASUSTeK model: STRIX Z270G GAMING v: Rev 1.xx serial: <filter> 
           UEFI [Legacy]: American Megatrends v: 1301 date: 03/14/2018 
CPU:       Topology: Quad Core model: Intel Core i7-6700K bits: 64 type: MT MCP arch: Skylake-S rev: 3 L2 cache: 8192 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 64128 
           Speed: 800 MHz min/max: 800/4200 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 800 5: 800 6: 800 7: 800 8: 800 
Graphics:  Device-1: NVIDIA GM204 [GeForce GTX 980] vendor: ASUSTeK driver: nvidia v: 440.26 bus ID: 01:00.0 
           Display: x11 server: X.Org 1.19.6 driver: nvidia unloaded: fbdev,modesetting,nouveau,vesa 
           resolution: 3840x2160~60Hz 
           OpenGL: renderer: GeForce GTX 980/PCIe/SSE2 v: 4.6.0 NVIDIA 440.26 direct render: Yes 
Audio:     Device-1: Intel 200 Series PCH HD Audio vendor: ASUSTeK driver: snd_hda_intel v: kernel bus ID: 00:1f.3 
           Device-2: NVIDIA GM204 High Definition Audio vendor: ASUSTeK driver: snd_hda_intel v: kernel bus ID: 01:00.1 
           Device-3: C-Media type: USB driver: hid-generic,snd-usb-audio,usbhid bus ID: 1-5:3 
           Device-4: Logitech Webcam C270 type: USB driver: snd-usb-audio,uvcvideo bus ID: 1-10:6 
           Sound Server: ALSA v: k4.15.0-66-lowlatency 
Network:   Device-1: Intel Ethernet I219-V vendor: ASUSTeK driver: e1000e v: 3.2.6-k port: f000 bus ID: 00:1f.6 
           IF: enp0s31f6 state: down mac: <filter> 
           Device-2: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter vendor: ASUSTeK driver: ath10k_pci v: kernel 
           port: e000 bus ID: 04:00.0 
           IF: wlp4s0 state: up mac: <filter> 
Drives:    Local Storage: total: 2.05 TiB used: 262.43 GiB (12.5%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 850 PRO 256GB size: 238.47 GiB 
           ID-2: /dev/sdb vendor: Samsung model: SSD 850 EVO 1TB size: 931.51 GiB 
           ID-3: /dev/sdc vendor: Samsung model: SSD 850 EVO 1TB size: 931.51 GiB 
Partition: ID-1: / size: 209.84 GiB used: 24.34 GiB (11.6%) fs: ext4 dev: /dev/sda2 
           ID-2: /home size: 907.37 GiB used: 238.10 GiB (26.2%) fs: ext4 dev: /dev/sdc1 
           ID-3: swap-1 size: 16.02 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sda1 
Sensors:   System Temperatures: cpu: 23.0 C mobo: N/A gpu: nvidia temp: 54 C 
           Fan Speeds (RPM): cpu: 0 gpu: nvidia fan: 18% 
Info:      Processes: 313 Uptime: 14m Memory: 15.60 GiB used: 2.50 GiB (16.1%) Init: systemd runlevel: 5 Compilers: gcc: 7.4.0 
           Shell: bash v: 4.4.20 inxi: 3.0.32 
thor@thor ~ $ 

No way to fix this please?

**Comment by Tetractys** [comment]
__SOLVED__
go to https://github.com/qbittorrent/qBittorrent/issues/11149#issuecomment-530864855

**Comment by Tetractys** [comment]
Admin, you can consider this issue solved. ty!
