### ISSUE TITLE
4.2 plugin support?

### ISSUE THREAD

**Issue by Bazzu85** [qbittorrent/search-plugins#120]
Hi,

as title...

are the plugins been ever updated to work with 4.2 version?

thx

**Comment by thalieht** [comment]
4.2 didn't break them.

**Comment by ImportTaste** [comment]
They're broken for me, too. I think it has to do with having Python 3.7 installed.

**Comment by Bazzu85** [comment]
> 4.2 didn't break them.

So, what broke the plugins? 
Maybe last version of python? 

The list is empty and trying to update give many errors

**Comment by ngosang** [comment]
I have tested:
* qBittorrent 4.2.0 with Python 3.7.2 in Windows 10
* qBittorrent 4.2.0 with Python 3.8 in Linux

Both are working well.
I tested only the official / included plugins. I don't have unofficial plugins.

**Comment by ngosang** [comment]
If you are having problems, you can try to remove the folder with the plugins:
    Windows: %localappdata%\qBittorrent\novaX
    Linux: ~/.local/share/data/qBittorrent/novaX
    OS X: ~/Library/Application Support/qBittorrent/novaX

**Comment by Bazzu85** [comment]
> I have tested:
> 
> * qBittorrent 4.2.0 with Python 3.7.2 in Windows 10
> * qBittorrent 4.2.0 with Python 3.8 in Linux
> 
> Both are working well.
> I tested only the official / included plugins. I don't have unofficial plugins.

So maybe I'm wrong but... I don't have any type of plugin..
Niether official or unofficial.. 

Any suggestion?

**Comment by Bazzu85** [comment]
> If you are having problems, you can try to remove the folder with the plugins:
> Windows: %localappdata%\qBittorrent\novaX
> Linux: ~/.local/share/data/qBittorrent/novaX
> OS X: ~/Library/Application Support/qBittorrent/novaX

In the appdata folder I have only nova and nova3 folder.. 
Deleting the 2 folder and opening qbittorent cause to recreate the nova3 one.. 
In any case I don't have any plugin under the search tab..

**Comment by alystair** [comment]
I discovered that accidentally installing an older version of Python over a newer one results in plugins 'vanishing' until update (because nova folder doesn't exist yet) - as well as results potentially not being displayed at all even if updated for whatever reason. Removing the older version of Python made things work again and 'nova' folder could be removed.
