### ISSUE TITLE
Jackett's Search/RSS stopped working with QBT 4.2.1

### ISSUE THREAD

**Issue by zutch93** [qbittorrent/search-plugins#122]
as the title says, Search doesn't work with Jackett, if i disable Jackett's  plugin and try to search 
![image](https://user-images.githubusercontent.com/31257994/72818861-d8d60900-3c74-11ea-97ff-5748c0b153ff.png)

when it's enabled i get this error:
![image](https://user-images.githubusercontent.com/31257994/72820894-623b0a80-3c78-11ea-927d-4e6afa84537b.png)

when Jackett plugin is not enabled but the rest are, i get no results.

and i double checked the json file 

![image](https://user-images.githubusercontent.com/31257994/72821065-a3331f00-3c78-11ea-900d-5acd537384b1.png)

which matches my Jackett's API key in the web UI
these are my Jackett's settings, the proxy works, i use it qbittorent too.
![image](https://user-images.githubusercontent.com/31257994/72821136-c1008400-3c78-11ea-841e-3b4395787e5a.png)

Jackett used to work just fine, am not sure what went wrong...

**Comment by ngosang** [comment]
I just tested it with qBittorrent 4.2.1, Python 3.7.2, Jackett 0.12.1623, Windows 10. It's working as expected.
Your config file looks good. Please post the version of your software (get the python version from qBittorrent logs)

**Comment by zutch93** [comment]
> I just tested it with qBittorrent 4.2.1, Python 3.7.2, Jackett 0.12.1623, Windows 10. It's working as expected.
> Your config file looks good. Please post the version of your software (get the python version from qBittorrent logs)

1/22/2020 10:29 AM - Python detected, executable name: 'python', version: 3.7.2

**Comment by zutch93** [comment]
i don't know what changed, i didn't do anything but the next morning when i turned on QBT to download/seed, Jackett worked, search worked, and RSS worked.
