### ISSUE TITLE
Add TorrentGalaxy as official and remove btbit and extv

### ISSUE THREAD

**Issue by libellula** [qbittorrent/search-plugins#123]
@ngosang my recommendation is to add this increasingly popular website which reminds of extratorrent while removing the now gone btbit and tvseries-specific only eztv (move it to the unofficial list).

**Comment by ngosang** [comment]
This repository is not maintained. Please, take a look at https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin
