### ISSUE TITLE
Bug: QBT doesn't start automatically the Jackett windows service

### ISSUE THREAD

**Issue by WiliTest** [qbittorrent/search-plugins#124]
Since I updated QB, the search engine does not work (on win10). The search result lead me to this page: https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin 

The `jackett.json` code is the same, so the `api_key` might have change. So I'm looking for it, but this sentence in the doc isn't clear "you can find it on top of Jackett UI". What/where is the "jackett  UI"?

**Comment by WiliTest** [comment]
Ok I  finally got it (jackett came with QBT, I did not know anything about it)
Jackett was installed as a service, I just clicked on "start", and it works. The QBT/Jackett/docs should mention it (and point to the jacket install docs. I edited it, hopefully without any mistake).

So in brief there is a little **bug: QBT should start the jacket service when needed.**

(So I changed the title of my post (the old one was: 
api_key: "you can find it on top of Jackett UI" meaning? (update broke the search) 
)

**Comment by WiliTest** [comment]
actually I still have a problem 

I guess **QBT should be able to start the service when needed, but it doesnt. I need to manually start the service to use it**. 

Any idea how to solve this? 

(on  Windows 10 with the last stable version of QBT) 
Print screen of the jacquet service property, and (below) of the error showing in QBT search result:
![jacket](https://user-images.githubusercontent.com/24194840/81467319-39fbfb00-91d8-11ea-8474-ee23f3426c16.png)

**Comment by ngosang** [comment]
qBittorrent is not able to start/stop Jackett service on demand. You can configure Jackett service to start on system start.
