### ISSUE TITLE
LimeTorrents, The Pirate Bay, Zooqle - "Retrieving metadata"

### ISSUE THREAD

**Issue by Noxillio** [qbittorrent/search-plugins#137]
When choosing a torrent from Limetorrents.cc, metadata is never retrieved and the torrent stays at 0.0% downloaded. [I was told to come make an issue here about it.](https://github.com/qbittorrent/qBittorrent/issues/12811#issuecomment-626400744)

EDIT: Added the other search plugins that I've noticed have the same issue.

**Comment by ngosang** [comment]
I just tested those trackers and they are working. Both, search and download.
Make sure you have Python3 installed in your machine (and Python > 3.4). Update the plugins in qBittorrent. Try to download from limetorrents using your web browser (it can be a DNS blockage or something).
If none of these are working for you, try Jackett.
