### ISSUE TITLE
rarbg plugin misses some search results

### ISSUE THREAD

**Issue by AlawamiAZ** [qbittorrent/search-plugins#138]
rarbg search plugin doesn't show sometimes doesn't show some results

for example, if you search for "Ori_and_the_Will_of_the_Wisps-HOODLUM" in rarbg site you get 1 result. If you search for the same term in qbittorrent it doesn't get any result from rarbg.

also searching "Ori and the Will of the Wisps" doesn't show anything from rarbg in qbit but in the website you get 1 result

**What WORKS**: searching for "Wisps-HOODLUM" does show a result. so it's probably the underscore causing some issue?

qbit version 4.2.5, updated plugin to 2.12

**Comment by ngosang** [comment]
Sorry, I can't fix that. We can't use the rarbg page to do the searches because they have captcha and other security measures. We are using a 3rd party API that works well in most cases, but the search is less accurate than the web page.
