### ISSUE TITLE
Errors attempting to install Official Search plug-ins

### ISSUE THREAD

**Issue by mulox1** [qbittorrent/search-plugins#14]
Apologies in advance, I am new here (as of today) so maybe I am just doing something wrong. I am running qBittorrent 4.0.1 64-bit on a Windows 10 machine.  I was able to install a dozen or so "unofficial" plug-ins with no problem, so I do know some of them work.  

**Steps to recreate:**
1. Download offical search plugin .py files from master
2. Open qBT 4.0.1 client and click on Search tab
3. Click the Search Plug-ins button
4. Click "Install a New one"
5. Click "local file"
6. Select a plug-in that was downloaded
The following error is displayed: Couldn't install "piratebay" search engine plug-in. Plug-in is not supported

**Comment by Shachar2like** [comment]
if you look at the unofficial plugins it's not listed there.
where did you find the link to the official plugins?

**Comment by mulox1** [comment]
Can't recall now, but it was on one of the Wiki pages.
So can you tell me why these official ones don't work?
Are these not supposed to be published for some reason?
Was really wanting the Pbay one and it seems pointless to make one if it
already exists...

**Comment by Chocobo1** [comment]
@mulox1 
You should be able to install all official plugins by clicking "Check for updates" button in qbittorrent.

**Comment by vovokrall** [comment]
@Chocobo1 Thank you SO MUCH!!! I was really missing PirateBay. 

About the unnofficial search plugin for SumoTorrents, does anyone have a fix? I can do searches, but I can't never download directly from qBitTorrent. I have to open the page description and use the magnet link.

**Comment by Chocobo1** [comment]
>About the unnofficial search plugin for SumoTorrents, does anyone have a fix? 

Probably won't fix, see: https://github.com/ngosang/qBittorrent-plugins/issues/2

**Comment by hannsen** [comment]
sumotorrent is fixed

**Comment by AnthonyBe** [comment]
I've been trying to install the new SumoTorrent  v1.4 script and I get an error:

`Couldn't install "sumotorrent" search engine plugin. Plugin is not supported.`

I'm using qB 4.0.4 64-bit on Win10

**Comment by zszabo2000** [comment]
Reinstalling ActivePath Python (and making sure it was being run by qBittorrent, by looking at the log in LOCALAPPDATA) allowed me to get my plugins working again. Until then, I had the same problem. In reality, it wasn't the plugin scripts that were incompatible, but rather the Python interpreter.

**Comment by AnthonyBe** [comment]
I'm pretty sure Qb is finding my Python OK.
On startup the following is in the log:
```
(I) 2018-04-29T13:51:17 - Python version: 2.7.14
(I) 2018-04-29T13:51:17 - Python found in PATH: D:\Python27\;D:\Python27\Scripts;<remainder of path removed>
```
..and I can open a command prompt in any location, run 'python', and it runs fines.

**Comment by hannsen** [comment]
sumotorrent ist v1.5, so you don't have the right one.
also sumotorrent is only tested with python 3

**Comment by AnthonyBe** [comment]
It would be great if the sumotorrent plugin could be written to also support Python 2 for backward compatibility (and also the fact that most of the plugins support Python 2 and 3)
