### ISSUE TITLE
qBittorrent(v4.2.1) Search crash during search on MacOS 10.14.6

### ISSUE THREAD

**Issue by ram19890** [qbittorrent/search-plugins#140]
Python quits unexpectedly after or during search process.
Python3 Version: 3.8
Python Old Version: 2.7(System App)
I am getting this message for a very long time for all version of qbittorrent and python versions, is there anything to do with old python version on MacOS?
[error.txt](https://github.com/qbittorrent/search-plugins/files/4727308/error.txt)

**Comment by ngosang** [comment]
The log say that you have Python 3.7 not Python 3.8. Python 2 is not required by qBittorrent. This is the first time I see that error.
@Piccirello @FranciscoPomba @Chocobo1 could you help?

**Comment by ram19890** [comment]
[python_v3_7.txt](https://github.com/qbittorrent/search-plugins/files/4740667/python_v3_7.txt)
[python_v3_8.txt](https://github.com/qbittorrent/search-plugins/files/4740668/python_v3_8.txt)

Oops, I have installed both python 3.8 standalone for MacOS and 3.7 from brew, I will try removing 3.8!
