### ISSUE TITLE
Plugins don't work with Python 3.9

### ISSUE THREAD

**Issue by IdrisKalp** [qbittorrent/search-plugins#143]
OS is Windows 10. Python 3.9.0rc1 installed. Qbittorrent version is 4.2.5. When I try to install plugins via checking for updates, I'm getting this message:

`Couldn't update "xxx" search engine plugin. Plugin is not supported.`

This error doesn't happen with Python 3.8

**Comment by ngosang** [comment]
I tested all the plugins in Linux with Python 3.9.0rc1 and it's working fine.
I can't test in Windows but I think this is because it's a RC version (we are not parsing well the Python version number). It will work when they release 3.9.0 final. If you have problems then I will reopen.
