### ISSUE TITLE
Cannot access http://127.0.0.1:9117/UI/Dashboard#

### ISSUE THREAD

**Issue by Olivier-Levasseur** [qbittorrent/search-plugins#146]
Hi, I installed Python 3.9 and the last Jackett but I cannot reach the Jacket UI anymore, so I can't view the API Key to put it in the Jackett.json.
Please help.. I'm using MacOS (10.15.7).. when I installed Jackett it said "service running", but I don't know how to check if it's currently running

**Comment by ngosang** [comment]
Well, the issue is not in qBittorrent, it's in Jackett. You can ask for help in Jackett's Discord channel => https://discord.gg/J865QuA

**Comment by Olivier-Levasseur** [comment]
ok, thanks
