### ISSUE TITLE
Clicking download does nothing (else than changing the font color of selected link to pink)

### ISSUE THREAD

**Issue by WiliTest** [qbittorrent/search-plugins#147]
I'm using the last qbt version (4.3.0.1) on  Windows 10  64 bit. 

The search use the jacket plugin as expected. The result shows as expected. 

But clicking download, doesn't do anything else than changing the font color of selected link to pink.

(The little window made to choose what we want for this file isn't showing as expected). 

It only shows when I copy the hash (from the "description page"), and use the button "add torrent link"

Any idea what could go wrong?

related: 
same problem on Linux: https://qbforums.shiki.hu/viewtopic.php?t=7388

**Comment by p060477** [comment]
but have you installed jackett on yr pc?
and have you set it?

**Comment by WiliTest** [comment]
yes, I'm starting the service each time I use the QBT search. (And without jacket, no result would show, so the problem doesn't seem to come from this)

**Comment by p060477** [comment]
...in my modest opinion when qbit has decided to use jackett as search engine only it was a very infaust choice…
i really do not want to install such sw on my pc…
so for me the only way is to use an old qbit vers which up to now works very very fine..easy..and without other sw installed on my pc..and its -service- too…
;)
IMHO

**Comment by thalieht** [comment]
>i really do not want to install such sw on my pc…
so for me the only way is to use an old qbit vers which up to now works very very fine..easy..and without other sw installed on my pc..and its -service- too…

You can just disable the jackett plugin.

**Comment by p060477** [comment]
also in thre very latest qbit vers?
is there still the choice NOT to use only jackett but the old comfortable way..??

**Comment by thalieht** [comment]
>also in thre very latest qbit vers?
>is there still the choice NOT to use only jackett but the old comfortable way..??

Yes

**Comment by WiliTest** [comment]
I'm closing this issue because it's now working (yesterday it did not). Maybe because I rebooted the computer. No idea.

**Comment by WiliTest** [comment]
I'm reopening it because it came back. (It works only sometime).

**Comment by ngosang** [comment]
Well, it's working for me in Linux and Windows. Make sure you have the plugins updated.
