### ISSUE TITLE
unable to install search plugins for qbittorrent

### ISSUE THREAD

**Issue by Im2dumb4this** [qbittorrent/search-plugins#149]
Im trying to add search plugins but every time I click to download it opens to a page of script (this has happened on every plugin). I have tried to download on both Brave and Safari and always the same problem. I have the most up to date version of qbittorrent (4.3.1). I noticed it mentioned Python on the download page and my computer seems to have Python launcher 3.8. I am working off a 2020 Macbook Pro. Can someone tell me what I am doing wrong?

**Comment by ngosang** [comment]
Yes, that script is the plugin (is Python language code).
You have to save that file in your pc with ".py" extension and import it in qBittorrent.
