### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Maikhi** [qbittorrent/search-plugins#157]
The conversion of these fine search plugings from **qbittorrent** to **PopcornTime** would be very useful when user has to search for something in a language different of the std english.

**Comment by ngosang** [comment]
Your request is not clear to me. qbittorrent and PopcornTime are totally different projects and we want to keep the search feature.
If you want to use qBittorrent with other torrent sites you can use:
* Jackett
* https://github.com/qbittorrent/search-plugins/wiki/Request-unofficial-search-plugin
