### ISSUE TITLE
API Issues for Dummies

### ISSUE THREAD

**Issue by johnsageeek** [qbittorrent/search-plugins#158]
I have found jackett.json and for the most part understand its structure. But for the life of me I cannot figure out how the API code, "on top of Jackett" as referenced in the "How to configure Jackett plugin" [page](https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin) Forgive me for being ignorant, but [Jackett API Key (you can find it on top of Jackett UI)
Can someone please help me to clarify what I am looking for.? Thanks in advance

**Comment by ngosang** [comment]
I added a Jackett screenshot in the documentation => https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin#configuration-properties

As you should know, Jackett is an external program that you have to install somewhere. Follow the Jackett install instructions to and open the Jackett UI in your web browser.
