### ISSUE TITLE
Can I add a Chinese search plug-in?

### ISSUE THREAD

**Issue by hexianfu** [qbittorrent/search-plugins#16]
English search website input Chinese no result?

**Comment by Shachar2like** [comment]
you can add a plug in that searches a Chinese website.
or do you mean that when you write Chinese on an English website you don't get any results?
they may not have any Chinese files

**Comment by hexianfu** [comment]
@Shachar2like  You do not have Chinese plug-in here, how do I add?

**Comment by Chocobo1** [comment]
@hexianfu 
I see there are 2 plugins for sites in China (author: hannsen), maybe you want to try it out.

Closing as "Not an issue".
