### ISSUE TITLE
WebUI not able to grab magnet link on 1337x

### ISSUE THREAD

**Issue by xerosys** [qbittorrent/search-plugins#160]
![image](https://user-images.githubusercontent.com/58919902/105620825-b742bc80-5db5-11eb-8bc5-201fdcc53913.png)

Running qBittorrent v4.2.5 WebUI on Docker on Synology NAS.  Search plugin works well on most sites, but on 1337x it fails to grab the magnet link.  Instead it just shows the description page URL.

**Comment by lproto** [comment]
Same on v4.3.3 Web UI, Ubuntu.

**Comment by ngosang** [comment]
1337x has enabled Cloudflare protection and we can not bypass this protection.
If someone is interested in using this indexer take a look at Jackett project.
https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin

**Comment by ngosang** [comment]
Plugin removed in #171
