### ISSUE TITLE
How to add a local proxy to search engine plugin.

### ISSUE THREAD

**Issue by laokong4628** [qbittorrent/search-plugins#161]
Add local proxy: http:\\127.0.0.1:port proxy 

prevent the search engine can not access network . hope get a help. thanks.

this code maybe work on python3?
import urllib2, feedparser
proxy = urllib2.ProxyHandler({"http":"proxy:port"})
d = feedparser.parse('https://www.zhongzidaohang.cn/', handlers = [proxy])

**Comment by ngosang** [comment]
The search plugins will use the same proxy configuration you configured in qBittorrent settings.
