### ISSUE TITLE
I'm not sure whether this is a bug or a suggested feature, really.

### ISSUE THREAD

**Issue by pjones112000** [qbittorrent/search-plugins#162]
I've had issues on occasion where the queue is essentially blocked from downloading anything with a bunch of "Downloading Metadata" that never get anything.  If I delete them, then it can move on to the next and continue.  I'm not sure whether this is due to an error or if there is a setting somewhere that I overlooked that allows you to set a limit that says to timeout on a "Downloading Metadata" or others that aren't actually doing anything and try later.  In this case, they look like they have been in there for days....they are considered "active".  Perhaps it might be more prudent to not make them Active until they are actually actively transferring content?  Please let me know if 1) there is a setting that I overlooked or 2) if this is submitted in the wrong place.

**Comment by ngosang** [comment]
This issue is not related to search plugins.
You have to report it in qBittorrent Core repository => https://github.com/qbittorrent/qBittorrent/issues
