### ISSUE TITLE
Select and Install New Plugin from UI

### ISSUE THREAD

**Issue by sirinath** [qbittorrent/search-plugins#163]
Instead of having to suppling the URL of each plugin is i possible to be able to install each plugin from the UI

**Comment by p060477** [comment]
..should be very usefull and time-saver...we really hope the programmers reply here.. ;)

**Comment by ngosang** [comment]
All official plugins are installed in qBittorrent by default.
If you want to add unofficial plugins you can do it with the URL or opening the `.py` file from your file system.
https://github.com/qbittorrent/search-plugins/wiki/Install-search-plugins
If you mean listing all unofficial plugins in qBittorrent UI to make the install easier I think this won't be implemented. We can't guarantee the software quality in that case.
