### ISSUE TITLE
jackett plug in not working...

### ISSUE THREAD

**Issue by p060477** [qbittorrent/search-plugins#165]
i've qbittorrent 4.2.5
 Jackett Version v0.17.743 
but it does not work at all..it does not find even if i type ubuntu in search box.. :(
![Immagine](https://user-images.githubusercontent.com/12773559/111882351-67e3cb80-89b5-11eb-92bb-01d8f2df0f6d.jpg)

**Comment by navjunk** [comment]
Configure indexers first.

**Comment by p060477** [comment]
done!
 now it works!
 but , in the jackett console is there the only option of -manual search-..??
 thxs for yr helping!
 cheers!

**Comment by p060477** [comment]
in the main window if i put my searched item in tab search and click enter i do not have nothing..i have only to click on manual search and go to the other page of the cvondsole..??

**Comment by navjunk** [comment]
I am not sure if I follow your query but if you mean that manual search in Jackett is working but jackett search is not working in qBittorrent (in windows) then, you need to create and place the jackett.json file in the nova engines folder. Follow instructions here: [configuring jackett](https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin)

For me, it worked as expected in windows, I am only facing issues in the setup explain in my post above.

**Comment by navjunk** [comment]
First window is to search indexers like 1337x (from your selected ones) so that you may locate them easily to any indexer specific configuration/ testing. Green 'Manual Search' is to search the content at the selected indexers, which is the search that users need.

But, if you use the jackett.json file appropriately as described then you will not need to open the jackett ui unless you are configuring or testing jackett/ indexers itself.

**Comment by p060477** [comment]
thxs so much again for yr helping and patience too..
i got this error trying a search in manual search and in qbittorrent, already had configured jackett.jason..,
i copy past here..i'd like to know a yr opinion about..:

System.Exception: Error while parsing field=category, selector=, value=logiciels: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1568
03-24 17:03:14 Error CardigannIndexer (epizod): Error while parsing row '
<li class="ilovewp-post ilovewp-post-archive clearfix post-7152 post type-post status-publish format-standard has-post-thumbnail hentry">
        <article id="post-7152">
                <div class="post-cover-wrapper">
                        <div class="post-cover">
                                <a href="https://wwv.epizod.tv/kali-linux-64-bits/" title="Kali Linux 64 bits">
                                        <img width="340" height="240" src="data:image/gif;base64,R0lGODdhAQABAPAAAP///wAAACwAAAAAAQABAEACAkQBADs=" data-lazy-src="https://www1.cpasbiens.to/img/logiciels_19801.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="Kali Linux 64 bits" title="Kali Linux 64 bits">
                                        <noscript>
                                                <img fifu-featured="1" width="340" height="240" src="https://www1.cpasbiens.to/img/logiciels_19801.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="Kali Linux 64 bits" title="Kali Linux 64 bits">
                                        </noscript>
                                </a>
                                <span class="post-meta-category">Non classé</span>
                        </div>
                        
                </div>
                
                <div class="post-preview">
                        <p class="post-meta">
                                <span class="posted-on">
                                        <span class="genericon genericon-time" aria-hidden="true"></span>
                                        <time class="entry-date published" datetime="2019-03-27T18:12:44+00:00">
                                                <a href="https://wwv.epizod.tv/kali-linux-64-bits/" title="Kali Linux 64 bits">mars 27, 2019</a>
                                        </time>
                                </span>
                        </p>
                        
                        <h2 class="title-post">
                                <a href="https://wwv.epizod.tv/kali-linux-64-bits/" rel="bookmark">Kali Linux 64 bits</a>
                        </h2>
                        <p class="post-excerpt">Kali Linux est une distribution GNU/Linux sortie le 13 mars 2013, basée sur Debian. La distribution a pris la succession de Backtrack, qui était basé sur Slackware jusqu'à la version 3 puis Ubuntu depuis la version 4. Backtrack était issu de la   Torrent permet de télécharger des torrents de films, séries, musique, logiciels et jeux. Accès direct à 49110 torrents sans inscription et sans ratio !</p>
                </div>
                
        </article>
        
</li>':

System.Exception: Error while parsing field=category, selector=, value=logiciels: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1568

**Comment by navjunk** [comment]
I am a user like you. The system.exception can be understood and guided by the qBittorrent plugins team. I guess you wait till they pick this up.

**Comment by p060477** [comment]
anyway i want to thank you so much indeed from the very deep of my heart,
cause you helped me so much with kind patience
cheers

**Comment by ngosang** [comment]
Jackett's errors like this should be reported in Jackett's GitHub page:
```
System.Exception: Error while parsing field=category, selector=, value=logiciels: Object reference not set to an instance of an object.
at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1568
```
