### ISSUE TITLE
Jackett Plugin seems to be installed but the GUI is not showing (TrueNas:FreeBSB) 

### ISSUE THREAD

**Issue by peter2cfu** [qbittorrent/search-plugins#166]
I have done a clean install for qbittorrent using a dedicated Jail, all seems to be working, the search functionality minus the Jackett plugin works as expected.

I have edited jackett.json file  as per [How to configure Jackett plugin](https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin) at location ~/.local/shares/qBittorrent/nava3/engines 
`{
    "api_key": "YOUR_API_KEY_HERE", 
    "tracker_first": false, 
    "url": "http://172.16.198.40:9117"
}`

My issue seems to be no matter what I do the I cannot gain access to the Jackett GUI in order to get the api_key.

Any advice would be appreciated even just where to look, I can normally solve most issues eventually but this one has me stumped.

**Comment by peter2cfu** [comment]
seems I managed to get it all working as a standalone item however integration into qbittorrent brings an error`Jackett: api key error! Right-click this row and select 'Open description page' to open help. Configuration file: '/.local/share/qBittorrent/nova3/engines/jackett.json' Search: 'Babylon 5'`
I guess I'm missing something here but can't work it out, for now, it works as a standalone application fine.

If anyone got Jackett+qbittorrent under Linux I love to hear from you.

**Comment by navjunk** [comment]
Hi peter2cfu, How did you install Jackett, did you use mono or something else?

**Comment by peter2cfu** [comment]
Hi navjunk, I got it all working finally,  the full blow by blow account here:
https://www.truenas.com/community/threads/unable-to-install-qbittorrent-search-plugins.88808/
