### ISSUE TITLE
Wiki Page was Renamed Incorrectly 

### ISSUE THREAD

**Issue by dembeck** [qbittorrent/search-plugins#168]
Looks like the last commit to this page needs to be rolled back

https://github.com/qbittorrent/search-plugins/wiki/shit

**Comment by dembeck** [comment]
This one too

https://github.com/qbittorrent/search-plugins/wiki/fuck2

might want to look over the changes made by Goku6 over the last few hours

**Comment by dembeck** [comment]
I see the problem... The permissions are set for anyone to make any edits to the wiki pages. I was able to remove the two links I listed above.

**Comment by ngosang** [comment]
Thank you for reporting. Someone already fixed it.
I can restrict the permissions but in that case most users won't share his plugins if they have to get approval...
For now I think this is working well enough and the page has a history that can be recovered. If you detect more vandalism open an issue. I can ban users too.
