### ISSUE TITLE
Jacket Plugin API problem

### ISSUE THREAD

**Issue by ben2talk** [qbittorrent/search-plugins#169]
I have read and tried to follow guides.
I configured Jackett. It looks good, with a couple of private trackers working nicely and returning search results.
https://i.imgur.com/AQp6PA2.png
So now I copy the API from Jackett and paste it in the json file... In the terminal we see Jackett is still running.
https://i.imgur.com/2s9pt9O.png
Following this I closed qbittorrent, rebooted, and still in qBittorrent the search returns 'Jackett: api key error!'
So what am I missing?

**Comment by navjunk** [comment]
Hi ben2talk, How did you install Jackett, did you use mono or something else?

**Comment by ben2talk** [comment]
I Name            : jackett
Version         : 0.17.946-1
Architecture    : x86_64
URL             : https://github.com/Jackett/Jackett

I cannot say what went wrong. I deleted the plugin and reinstalled, and this time around it worked - though I'm sure I pasted the API in exactly the same way...
