### ISSUE TITLE
Version 4.8.3 unsupport The lists plugins

### ISSUE THREAD

**Issue by BarryLoo** [qbittorrent/search-plugins#177]
The list is from the [official list](https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins#plugins-for-public-sites)

that is the log
* [qbittorrent.log](https://github.com/qbittorrent/search-plugins/files/7309986/qbittorrent.log)
* [qbittorrent_backup.log](https://github.com/qbittorrent/search-plugins/files/7309987/qbittorrent_backup.log)

**Comment by iczer02** [comment]
figured it out for me win10 appdata folder a bit screwy oh and python path     search box  advanced system properties environmental variables C:\Python\Python310 C:\Python\Python310\Scripts and no python remnants in any other folder that it shouldn't be solved for me.

https://www.technipages.com/windows-administrator-account-login-screen

**Comment by ngosang** [comment]
I'm using Python 3.10 in Windows 10 and it's working fine.
You can try to remove the folder => ` %localappdata%\qBittorrent\nova3`
And restart qBittorrent.
