### ISSUE TITLE
I never get search results

### ISSUE THREAD

**Issue by Maurafarah7** [qbittorrent/search-plugins#180]
Hi all, I'm using Qbittorrent v4.3.9 for Mac, and I never get any results in the search :-(

I´ve installed last Python version, added some several search engines...

But no luck, I don't understand, anyone can help me?

Thanks in advance!

Mauri

**Comment by tvqt** [comment]
I opened an issue under #187, could potentially be a fix? Let me know if it works for you!

**Comment by ngosang** [comment]
I don't know about macOS but it's working in Windows and Linux.
Install Python 3.10, delete this folder `~/Library/Application Support/qBittorrent/nova3` and restart qBittorrent.
