### ISSUE TITLE
Search plugins list is gone

### ISSUE THREAD

**Issue by Odyssey346** [qbittorrent/search-plugins#182]
I was gonna get the link for the list of search plugins for a friend, but when I came back to it I noticed it was gone. There's an archive [here](https://web.archive.org/web/20211126001654/https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins) in case someone wants to restore it.

**Comment by p060477** [comment]
thxs so much!
you have been so generous and kind!
have a nice sunday!
cheers!
:)

**Comment by Odyssey346** [comment]
Seems like it has been restored.
