### ISSUE TITLE
oxtorrent search plugin

### ISSUE THREAD

**Issue by p060477** [qbittorrent/search-plugins#185]
how to add this:
https://github.com/qbittorrent/search-plugins/pull/184/files/cfc84e94d8e5bb4f56bd22f0148c786c4fea20d1..edf70d7638e5a8bc927fc41537c5ed6e59e303ab#diff-c1d0600ffb641a180b44a88a2cc3263c620e0d0194de2ca9ce5593e226b0cdee

**Comment by ngosang** [comment]
https://github.com/qbittorrent/search-plugins/pull/184#issuecomment-991929929
