### ISSUE TITLE
[BUG] some searches using Jackett plugin doesn't show any results

### ISSUE THREAD

**Issue by masterofobzene** [qbittorrent/search-plugins#186]
Weird bug, some searches using jackett plugin doesn't return any results, while doing them directly on jackett UI do show results as expected:

![imagen](https://user-images.githubusercontent.com/94469116/145619293-c7c27d13-a94c-4163-8e44-06be985d4840.png)

and in jackett:

![imagen](https://user-images.githubusercontent.com/94469116/145619383-5887f1ac-431c-4636-8850-366257baee08.png)

**Comment by ngosang** [comment]
https://github.com/qbittorrent/search-plugins/issues/210#issuecomment-1257053813
