### ISSUE TITLE
No Search Engine Plugin is Supported

### ISSUE THREAD

**Issue by DanSherwind** [qbittorrent/search-plugins#188]
Hello everyone. I tried installing search engines from GitHub, (already have the ones that automatically update by default), by copying the code and putting into a .py file, but when I go to install them, they all come out as not supported.

**Comment by Korb** [comment]
> when I go to install them, they all come out as not supported.

https://github.com/qbittorrent/search-plugins/issues/193#issuecomment-1064724715
