### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by axiomregna** [qbittorrent/search-plugins#19]
how am i supposed to save these .py "files" ? the tutorial doesnt show how to do it, but it shows how to open a file in a program... i dont understand that. figure out the hard part on your own but we will show you the part that everybody knows. what do i save and how do i save it??

**Comment by buzzvicky** [comment]
You can:
A: Right click on a *.py file and select _save as_
B: Click on the *.py file; copy the content of the file to a new text file on your pc; save and rename the file you created from .txt to .py extension
