### ISSUE TITLE
Search Plugins Not Supported Despite 3.92 Python And Complete Re-Install

### ISSUE THREAD

**Issue by coffeecupman** [qbittorrent/search-plugins#193]
I've been unable to use search plugins since last summer when I migrated my qb from an old laptop to a new one.
qb 4.41, python 3.92 (64 bit), Windows 11 (although was Win 10 when the problem started). On my old machine I had all of the recommended search plugins on the github search plugins installed.

When I open the Search Plugins tab, there appear to be no plugins installed.

Any plugin I try to install says "Cannot install (X), plugin not supported."

I have tried a complete uninstall and reinstall, no change. Back in November when I had some time I also tried installing about four different Python versions above 3.0 to see if I could find one that the plugins would like.

I did a complete uninstall today, ticking all uninstall boxes, and searched for files and deleted them wherever I found any.

Despite the uninstall, after reinstallation of qb 4.41 when I hit "Check For Updates", the fresh install seems to know the names of all of the former plugins I had installed, and throws an error window for each of them giving the same error as above.

So it appears that there is a file somewhere that contains information on previous plugins that is not being successfully removed with a full uninstall, and the remnants of these old plugins are somehow contaminating their successful re-install. That is my theory based on what I've tried so far. I am not a programmer and I'm not sure.

Does anyone have any idea what I could delete or do to give me a fresh start with search plugins?

I'm happy to provide any logs or information requested to help troubleshoot, or some details which I may have missed which are critical to going further with this.  Thanks.

**Comment by chuacw** [comment]
Install Python 3.8.5 and you should be fine after reinstalling all the plugins again.

**Comment by coffeecupman** [comment]
> Install Python 3.8.5 and you should be fine after reinstalling all the plugins again.

Seriously, thank you so much. It took me a while before I could try this out but this has worked and I really appreciate your taking the time. All the best.

**Comment by ngosang** [comment]
I'm using Python 3.10 in Windows 10 and it's working fine.
You can try to remove the folder => ` %localappdata%\qBittorrent\nova3`
And restart qBittorrent.
