### ISSUE TITLE
Request: Add FossTorrents search plugin

### ISSUE THREAD

**Issue by DeflateAwning** [qbittorrent/search-plugins#197]
https://fosstorrents.com has open source software downloads. Would love if it was available as a search plugin.

**Comment by ngosang** [comment]
No more official plugins will be added.
You can request and unofficial plugin here => https://github.com/qbittorrent/search-plugins/wiki/Request-unofficial-search-plugin
Or write it yourself and add it to => https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins
