### ISSUE TITLE
Search Plug-Ins no longer auto-download when clicking the check for updates button

### ISSUE THREAD

**Issue by cyberfunk** [qbittorrent/search-plugins#199]
On a fresh install in the past QBittorrent would automatically download a shortlist of the best search plugins including Jacket simply by clicking the "check for updates" button. Now when I click "check for updates" button it says Plug-Ins are already up to date even though none are installed. I have to download  and install plug ins individually one by one using the GitHub repository. Is this new behavior or is my installation corrupted?

Qbittorrent 4.4.3.1
macOS Big Sur 11.6.6
Python 3.10.2

**Comment by Kekerykek** [comment]
Happens on my end as well. I like this new change actually, as some of the default sites were dead,

**Comment by cyberfunk** [comment]
I didn't mind the dead sites as the list of sites automatically imported was already very small to begin with anyway. It's just annoying to have to go to the GitHub site and add them manually. I say bring back the auto search plug-in installation. As long as they include the sites listed in the attached image you're good to go imho.
![Screen Shot 2022-06-17 at 3 04 29 PM](https://user-images.githubusercontent.com/12664589/174244309-806615f3-9de5-4511-a080-fdf36d3405f4.png)

**Comment by theuserwhoisnotadeveloper** [comment]
Happens on my qbittorrent too. none of the official ones are installabe neither locally nor as a web link. some unofficial ones are installable as local file but installing them as web link still doesn't work. I have to install flatpak version, then install the desired search plugins, and then copy nova3 directory of flatpak qbittorrent and paste it into regular qbittorrent's own directory.

qbittorrent 4.3.3.1
Fedora 36
python 3.10.5

**Comment by tw333k** [comment]
> I didn't mind the dead sites as the list of sites automatically imported was already very small to begin with anyway. It's just annoying to have to go to the GitHub site and add them manually. I say bring back the auto search plug-in installation. As long as they include the sites listed in the attached image you're good to go imho. ![Screen Shot 2022-06-17 at 3 04 29 PM](https://user-images.githubusercontent.com/12664589/174244309-806615f3-9de5-4511-a080-fdf36d3405f4.png)

Mine looks almost exactly the same. Does TorrentGalaxy work for you? When I try to search, nothing happens. I got RSS feeds working but not the search

**Comment by cyberfunk** [comment]
> > I didn't mind the dead sites as the list of sites automatically imported was already very small to begin with anyway. It's just annoying to have to go to the GitHub site and add them manually. I say bring back the auto search plug-in installation. As long as they include the sites listed in the attached image you're good to go imho. ![Screen Shot 2022-06-17 at 3 04 29 PM](https://user-images.githubusercontent.com/12664589/174244309-806615f3-9de5-4511-a080-fdf36d3405f4.png)
> 
> Mine looks almost exactly the same. Does TorrentGalaxy work for you? When I try to search, nothing happens. I got RSS feeds working but not the search

Yeah I just found out most of these don't work. The ones that DO work more than make up for it with search results so I never bothered to check them individually. For me 1337x, KickAss Torrent are the only two working.

**Comment by ngosang** [comment]
Official plugins are unmaintained for a long time.
I recommend you to use Jackett.
https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin

**Comment by tw333k** [comment]
I have jackett running on my Synology NAS but I can't get the qbittorrent plug in to work. connection error every time.

**Comment by cyberfunk** [comment]
> I have jackett running on my Synology NAS but I can't get the qbittorrent plug in to work. connection error every time.

I've never been able to get Jackett working and always uninstalled it in the past when the search plug-ins used to automatically install after hitting the "check for updates" button on a fresh install. Waste of time if you ask me.

**Comment by ngosang** [comment]
https://github.com/qbittorrent/search-plugins/discussions/235#discussioncomment-5959303
