### ISSUE TITLE
Not getting any search results [windows 10 ]

### ISSUE THREAD

**Issue by playmobilmeister** [qbittorrent/search-plugins#200]
**Problem**
I installed Jackett and the plugin according to instructions. Jacket works from the Web UI and I am already using it to find and download torrents. The plugin for QB, however, does not. I never get search results whatever I type in. The symbol on top of the search tab title is for half a second a white check mark on a black background and then it quickly changes to the familiar exclamation mark warning sign.
![image](https://user-images.githubusercontent.com/33288162/173001197-a653ab5e-b2a4-45a9-8f0a-f58081c75509.png)

**Setup**
windows 10 21H2
Qbittorrent 4.4.3.1 with Jackett plugin enabled and with the API key copied from the Jacket API
Jackett 0.20.1158

**Alternative**
Keep using Jacket from the web UI

**Comment by dissociativity** [comment]
For me all search plugins appear to be broken, all of them that previously worked now refuse to install, I'm wondering if python updates broke it or it's a regression in qbittorrent itself.

**Comment by tw333k** [comment]
mine are a mixed bag. Some work but others don't and I can't work out why

**Comment by ngosang** [comment]
Jackett plugin is working fine in Windows 10.

Check the qBittorrent log tab and check the Python version installed. It should be Python 3.10
`24/09/2022 22:01 - Python detected, executable name: 'python', version: 3.10.4`

Follow the instructions
https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin
