### ISSUE TITLE
Malformed configuration file.

### ISSUE THREAD

**Issue by tiritibambix** [qbittorrent/search-plugins#202]
Hello, I'm running qBittorrent v4.4.3.1 Web UI (64-bit) via docker on a debian machine.

I got volumes configured like this :
```
...
      - /srv/path/Files/QBittorrent:/config
...
```
When I try to setup Jackett plugin, I get this error message
>malformed configuration file. [...] Configuration file: '/config/data/nova3/engines/jacket.json'

My `jackett.py` is located in `/srv/path/Files/QBittorrent/data/nova3/engines` and it looks like this : https://pastebin.com/BM6Kj6Mn

My `jackett.json` is located in `/srv/path/Files/QBittorrent/data/nova3/engines` and it looks like this : 
https://pastebin.com/h7mEVah0

What am I doing wrong ?

**Comment by ngosang** [comment]
It looks good to me. Try to give the file more permissions eg; 777

https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin
