### ISSUE TITLE
RUTracker: Search without credentials

### ISSUE THREAD

**Issue by schnillerman** [qbittorrent/search-plugins#209]
Via "http://rutracker.org/forum/search_cse.php?q=", I'm able to search without credentials. This might be added to the corresponding plugin, if not already implemented.

**Comment by thalieht** [comment]
RUTracker is not an official plugin, you should contact it's author instead.

**Comment by ngosang** [comment]
You can see original author contact info here:
https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins
