### ISSUE TITLE
why do you limit some of your search plugins?

### ISSUE THREAD

**Issue by theuserwhoisnotadeveloper** [qbittorrent/search-plugins#216]
the title says it all, why doesn't the official search plugins like Solid Torrents and ThePirateBay show more than 100 search results? while the unofficial versions of ST and TPB show hundreds of even thousands of results, the official search plugins stop searching for torrents the moment they reach 100 search result. the official ST got released just 4 days ago, so the problem isn't the official search plugins not being up to date.

**Comment by ngosang** [comment]
Official plugins are installed by default and we limit the results to avoid harming the sites with a large number of requests. Unofficial plugins are not related to qBittorrent and they can do anything they want. You could use the unofficial plugin, make your own plugin or open a PR to modify the official plugin in some way that the number of requests is low.
