### ISSUE TITLE
Piratebay no results returned

### ISSUE THREAD

**Issue by Sp3EdeR** [qbittorrent/search-plugins#217]
When searching for an item that isn't found on the pirate bay, the site returns a "No results returned" search result. This result cannot be downloaded.

![noresultsreturned](https://user-images.githubusercontent.com/22780322/193010717-8d296a78-f47c-4ba8-aa30-bf51dd23405f.png)
![downloadingthis](https://user-images.githubusercontent.com/22780322/193010812-6d5e84f2-b32c-4466-b29e-1427eb8c6ec5.png)

PR #204 fixes the issue.
FYI @ngosang

**Comment by libellula** [comment]
This version works: https://scare.ca/dl/qBittorrent/thepiratebay.py

**Comment by Sp3EdeR** [comment]
It does not seem to work right for me, @libellula. Please find the screenshot of "No results returned" with your plugin version:
![PiratebayWithCategoriesResult](https://user-images.githubusercontent.com/22780322/218178091-bcbcd1a3-ad76-4889-9aef-e3420928d1fa.jpg)

**Comment by ngosang** [comment]
It's working. Probably it's blocked in your country.
I recommend you to use Jackett, it can use mirrors for TPB.

**Comment by Sp3EdeR** [comment]
Oh, it would be so nice if you just read it or looked at it, @ngosang. But okay, I guess you don't understand English. I guess it cannot be helped. 🙂

**Comment by ngosang** [comment]
Sorry, fixed here => https://github.com/qbittorrent/search-plugins/pull/237

**Comment by Sp3EdeR** [comment]
Oh! You DO understand English! :)
I think my PR (#204) would be a better solution, because the "No results returned" string may also have a Russian localization. That one filters torrents with hash value `0`.

**Comment by ngosang** [comment]
https://github.com/qbittorrent/search-plugins/pull/238
