### ISSUE TITLE
Unofficial plugin for mvgroup.org

### ISSUE THREAD

**Issue by ezekielar** [qbittorrent/search-plugins#23]
As far as I remember, there was a feature batch grabbing all the magnet/torrent links on a web page.
Is it possible to add this feature into the software, if not, can someone create a plug-in for the MVGROUP.org torrents?
Many thanks!

**Comment by ngosang** [comment]
Requested in https://github.com/qbittorrent/search-plugins/wiki/Request-unofficial-search-plugin
