### ISSUE TITLE
Jackett Problem

### ISSUE THREAD

**Issue by GitHub-Iridium** [qbittorrent/search-plugins#241]
I'm new to macOS (M2 Mac mini) so bear with me...

I get the following in search:

> Jackett: api key error! Right-click this row and select 'Open description page' to open help. Configuration file: '/Users/iridium-minus/Library/Application Support/qBittorrent/nova3/engines/jackett.json' Search: 'Amiga'

However, that directory does not exist for me, and, oh boy, _have_ I searched!

What idiotic thing am I doing wrong?

Thank you.

**Comment by ngosang** [comment]
The folder `/Users/iridium-minus/Library/Application Support/qBittorrent/nova3/engines` must exist. Could you post the list of files in that folder?

**Comment by WyvRevah** [comment]
It probably exits. That folder is probably hidden so you would need to do Shift+Cmd+"." to show it or search the path in Finder. I'm also having problems with the api key error and would appreciate if someone explained.

**Comment by aljustiet** [comment]
> The folder `/Users/iridium-minus/Library/Application Support/qBittorrent/nova3/engines` must exist. Could you post the list of files in that folder?

I don't have that folder:
$ ls -a /users
.          ..         .localized Library    Shared     aljsutiet
