### ISSUE TITLE
Error when in the search there's an apostrophe

### ISSUE THREAD

**Issue by luca-demma** [qbittorrent/search-plugins#245]
![image](https://github.com/qbittorrent/search-plugins/assets/67636104/9310c541-ed92-4277-a846-cbb98a888a39)
I get this error when in the search bar there's an apostrophe (maybe there's some problem with special characters?).
There is no error when using the same search term but without apostrophe

**Comment by ngosang** [comment]
Special characters are supported. Make the same query in the Jackett's UI to check if you have some indexer wrong.
