### ISSUE TITLE
I have uploaded all the plugins from this repo in 1 folder

### ISSUE THREAD

**Issue by bncal** [qbittorrent/search-plugins#246]
https://github.com/bncal/one-click-qbittorrent-searchplugins

I wanted to commit in this repo and provide the folder with 50+ plugins but I am not authorized to commit or create a pull request so i created mine that redirects here as well.

**Comment by ngosang** [comment]
This repository is official and it contains only the plugins provided by qBittorrent. You can share your plugins here => https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins
