### ISSUE TITLE
Mejortorrent plugin

### ISSUE THREAD

**Issue by Pireo** [qbittorrent/search-plugins#25]
http://www.mejortorrent.com/
The most popular spanish torrent site.
https://torrentnote.com/spanish-torrent-sites

@hannsen doable?

**Comment by hannsen** [comment]
yeah doable

**Comment by Pireo** [comment]
Look at this too: https://snowfl.com/
unlike btdb for example, it lists seeds and leech, verified or not, the source, has no ads/popups...
perhaps it's possible to use "redirect to dowload page" option in qBT to redirect to different sites.
I would propose this as official rather than MagnetDL now.
When you have time... if you're interested.

**Comment by hannsen** [comment]
this site would be a challenge, since its javascript based

**Comment by Pireo** [comment]
Fantastic job man. It also redirects to different sites as I predicted, I will definitely propose it as official.

**Comment by hannsen** [comment]
Its only python 3 and no category support, I doubt they will approve

**Comment by Pireo** [comment]
Mmmhhh it doesn't seem to work anymore.

**Comment by hannsen** [comment]
Fixed, either they changed their site randomly or they don't like plugins parsing it

**Comment by Pireo** [comment]
Thanks again.

**Comment by Pireo** [comment]
Hope it can still be fixed.

**Comment by hannsen** [comment]
snowfl is KO, I don't want to fix it everyday

**Comment by MaurizioRicci** [comment]
I created the plugin for mejorTorrents. It works except the download. 
Does anybody can understand why my download_file doesn't work in qBittorrent?

Testing with "python nova2dl.py http://www.mejortorrent.org http://www.mejortorrent.org/peli-descargar-torrent-19914-Sueno-en-otro-idioma.html" works fine.

And prints out: "C:\Users\Maurizio\AppData\Local\Temp\tmpmsayyec3 http://www.mejortorrent.org/uploads/torrents/tmp/torrent.php?table=peliculas/&name=Sueno_en_otro_Idioma_Hdrip_Latino.torrent"

Anyway it looks like qBt doesn't even call my function. The code is here: https://github.com/MaurizioRicci/qBittorrent_search_engine/blob/master/mejor.py
