### ISSUE TITLE
bt4g plugins error (failed to load the torrent)

### ISSUE THREAD

**Issue by gigend** [qbittorrent/search-plugins#252]
![image](https://github.com/qbittorrent/search-plugins/assets/54487902/6c5954dc-055d-430a-9f09-4bbfaf4e29c3)

I don't know how to fix it, the plugin that I downloaded is version 1.1, I have to have a web browser directly to get the magnet link, while other plugins don't have this kind of problem. is there any python code inside the plugins that needs fixing? because I don't really understand.

source plugins: https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins
source bt4g plugins: https://github.com/kjjejones44/b4tg_search_plugin

Thanks if anyone can fix this.

**Comment by ngosang** [comment]
It's an unofficial plugin. You should contact @kjjejones44
