### ISSUE TITLE
Request for The RarBg Plugin

### ISSUE THREAD

**Issue by Mr4x3** [qbittorrent/search-plugins#253]
Hi guys, we know rarbg is gone but some guys tried to re create it named https://TheRarBg.com https://www.reddit.com/r/TheRarBg/comments/13zkg8g/to_all_rarbg_refugees_build_from_what_was_left/ 

it have most of latest torrents, wanted to add it to my QBT.

Any help would be appreciated.

**Comment by MalinrRuwan** [comment]
Rarbg isn't gone ig. it's still there. check the new proxies. https://rarbg.gg/ some of these are working great. so make the y'all can remake the plugin

**Comment by Mr4x3** [comment]
It died mate https://en.wikipedia.org/wiki/RARBG

**Comment by ngosang** [comment]
The site is dead and I don't know if the copy cat sites are updated and safe.
