### ISSUE TITLE
Search plugin web address has changed

### ISSUE THREAD

**Issue by kiwichick888** [qbittorrent/search-plugins#254]
My apologies, I know this isn't to do with an official plugin but the plugin hasn't been updated for over two years and there doesn't seem to be any way to contact the developer. 

The web address for b4tg has changed from https://bt4g.org/ to https://bt4gprx.com/

Is there any way to edit the python script to update it, or would it require a complete re-write? I did edit it and just changed the URL and it installed into qBT but got no results from a search.

**Comment by ngosang** [comment]
We don't give support about unofficial plugins. You should contact the original author.
https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins
