### ISSUE TITLE
Improve Search

### ISSUE THREAD

**Issue by Chaython** [qbittorrent/search-plugins#258]
Instead of bringing up another prompt, to submit new plugins, why not just have a textbox entry on the search engine list?

Current list
![image](https://github.com/qbittorrent/search-plugins/assets/6486343/b69dabf8-6525-4538-b9e8-716e2c95d0e4)
Install new one brings up another prompt: local or weblink, weblink further changes the prompt to a text entry.
![image](https://github.com/qbittorrent/search-plugins/assets/6486343/c316261c-9740-4948-b70c-d97e9be63619)

I propose, you can put a file picker, and text entry in the list.
Either, an empty entry or in the header...

**Comment by ngosang** [comment]
You have to make the request in the main repository => https://github.com/qbittorrent/qBittorrent
This is just for search plugins.
