### ISSUE TITLE
BTDB gone and torlock is not safe anymore

### ISSUE THREAD

**Issue by Pireo** [qbittorrent/search-plugins#26]
@Chocobo1 
Ok, I post this issue here too. BTDB doesn't seem to work anymore unfortunately, and torlock does show strange results and the home page has "dating" and other suspicious options. Both the sites should be removed from the search engine. I recommend to add snowfl, limetorrents, and even academictorrents, etree and linuxtracker, since all these sites have 100% free content and this is important since qBt doesn't support piracy, and for the same reason they're unlikely to be shut down. Torrentz2 also should be placed in the unofficial list imho, since it's fake. Ah, a few cosmetic changes to show all the favicons are welcome too.

**Comment by Chocobo1** [comment]
>academictorrents

The site owner seems to have some concerns about adding to our official plugins, see: https://github.com/qbittorrent/search-plugins/pull/20#issuecomment-357514850

As for other requests, until I find someone who help maintain, I guess we're stuck here.

**Comment by Pireo** [comment]
BTDB is back now.

**Comment by Pireo** [comment]
@solenskiner are you interested in maintaining the search engine?

**Comment by Pireo** [comment]
@BrunoRex

**Comment by BrunoReX** [comment]
@Pireo is that an existing plugin for that site (even if it doesn't work anymore)?

**Comment by Pireo** [comment]
@brunorex What site?

**Comment by BrunoReX** [comment]
@Pireo You asked me if I want to maintain a search engine and I don't even know the URL for it...

**Comment by Pireo** [comment]
I meant the whole official list.

**Comment by msagebiel** [comment]
fyi https://github.com/Jackett/Jackett/issues/2753 rarbg needs update &app_id parameter

**Comment by BrunoReX** [comment]
Nope, don't have time for that sorry

**Comment by Pireo** [comment]
@BrunoReX ok, listen, can you make a plugin for http://www.mejortorrent.com/ ? I'ts the most popular spanish torrent site.
