### ISSUE TITLE
(Almost) Every possible plugin is not working after the 4.6 update

### ISSUE THREAD

**Issue by kamekku14** [qbittorrent/search-plugins#263]
Unfortunately, due to Python 3.7+ being the required minimum version for the Search feature, it looks like all the plugins aren't working in the new 4.6 update. I bet that **THIS SHOULD BE UPDATED ASAP! THIS IS IMPORTANT!**

**Comment by RobDean69** [comment]
I have the same issue. Be good to know which version of python works!

**Comment by kyleli666** [comment]
I have a similar issue here. I can confirm I used it on 2023 Dec 18, while qBit version should also be 4.6+, and I have python 3.11 and 3.12 installed, but suddenly I lost and cannot install or use any search plugin anymore today 2023 Dec 26.
I tried revert to 4.5, and also reinstall the python 3.10 which qBit automatically recommends and installs, but both do not help.
Really confusing...

**Comment by amccombsahce** [comment]
I am experiencing similar with qb 4.3.9, python 3.8.10, ubuntu 20.04, in that all the search engine plugins disappeared. I can add them back by copying the url and then Install a new one > Web Link > OK, after waiting 30 seconds it will bring all the search engines back, but only until the program exist, when I restart qb then I need to add the search engine again.
I have also noticed that when qb starts, there will be an the gray frame of qb but with black insides that lasts longer than usual like it's having trouble with something.

**Comment by darlopvil** [comment]
Me too, search engine doesn't work anymore.

**Comment by r1k0** [comment]
same here. MacOS, 4.6.2, python3.11, was working fine a week or 2 ago.
All plugins just disappeared and I can seem to be able to add any back, whether from link or local file.

Each and every time I get:

1) a pop up saying 'Plugin is not supported'
2) this error message from CLI
`Could not parse Nova search engine capabilities, msg:  Connection error: Not Found
<capabilities>
    <piratebay>
        <name>The Pirate Bay</name>
        <url>https://thepiratebay.org</url>
        <categories>music movies games software</categories>
    </piratebay>
    <pirateiro>
        <name>Pirateiro</name>
        <url>https://pirateiro.com/</url>
        <categories></categories>
    </pirateiro>
...`
Given the few seconds it takes before erroring out, it looks to me that the issue does not come from the software but from some connection that gets refused (wild guess). On top of that it seems cross platform (ubuntu user above) and not version related.

So my next clue question would be: what is raising this 'Could not parse Nova search engine capabilities, msg:  Connection error: Not Found' error?

**Comment by tuttuntep** [comment]
yep same here, end of december, week ago. doing exactly what you guys a saying. thats what i came here for, thought id find the answer....who do we speak to? they obviously dont use it, and don't look at these threads either?? suss az🤐🍕

**Comment by tuttuntep** [comment]
i messaged the man, toldm bout this thread. hopefully he sorts it and its not the latest feature due to misinformation legislations that appears also to spread as if a virus...fancy that?? need a vaccine to stop the legislation pandamic more than we need water almost now. seeyas, happy new year!!🥂🎆🎇🎈

**Comment by Nixflyn** [comment]
Reinstalling the latest version of Python with "add python.exe to PATH" selected worked for me. Without selecting that I still received errors when using plugins.

**Comment by kyleli666** [comment]
> Reinstalling the latest version of Python with "add python.exe to PATH" selected worked for me. Without selecting that I still received errors when using plugins.

This does not help in my case. Still all plugins are not supported.
![image](https://github.com/qbittorrent/search-plugins/assets/93997542/ec34f871-3e16-49a0-97bc-5c06d969edba)

**Comment by Nixflyn** [comment]
So sorry for presenting a solution that worked for me. I'll be busy using my plugins without a problem, good luck!

**Comment by darlopvil** [comment]
@lohtse don't be an asshole. He was only trying to help. Many other solutions have been proposed here and no one helped me neither, but at least, he suggested something that may solve the problem. Sadly, only devs can fix this.

@Nixflyn updated to the latest version of python. From 3.11.2 to 3.12.1. Thanks.

Meanwhile, we can keep waiting for an official communication or use another alternative and move on.

**Comment by kyleli666** [comment]
Hi @all, I have 2 windows PCs that are affected together recently, so it makes suspecting windows updates.
I found a work around to my case is to uninstall KB5033375 (Win11 22H2), and then my search plugins are back...

**Comment by p060477** [comment]
hi, BUG is sthill here after 2 years...how to finally solve this NIGHTMARE...??

**Comment by Saloframes** [comment]
I have not the slightest idea why, but updating to the latest version of the "cpasbien" unofficial plugin magically made search work again after getting the exact same errors. Found here: https://github.com/MarcBresson/cpasbien

**Comment by darlopvil** [comment]
> updating to the latest version of the "cpasbien" unofficial plugin 
@Saloframes 

SEARCH ENGINE WORKS AGAIN

IT'S BLACK MAGICK 🧙‍♂️🪄✡️🫡🪬💯🧚‍♀️

![imagen](https://github.com/qbittorrent/search-plugins/assets/60988792/950406fc-122a-442e-b103-b176fba06a9f)
![imagen](https://github.com/qbittorrent/search-plugins/assets/60988792/be1e037f-0d54-49f7-a6d5-a6ad2864154e)

**Comment by p060477** [comment]
maybe here someone is laughing at our back...and playing the fool of us...
mainly the devs who has shamely disappeared...

**Comment by darlopvil** [comment]
@p060477 

Two years ago, they announced that the search engine would be replaced by a direct communication with Jackett. There won't be any search engine plugins, but a built-in request with Jackett. See #121 
Also #241 was the last issue commented and tagged by devs, no more comments or "visible activity" appears to be from there.
And then this thread, which started in Nov '23. Full of requests to solve the problem and still with no official answer.

Everything indicates that this project if not is already dead, it's only a matter of time.

**Comment by p060477** [comment]
thxs for the history lesson...but...2 years of BUG means that they maybe abbandoned this search plug ins project BUT up to niow more then 2 years later ther is NO replace project at all
and this is a real SHAME

**Comment by darlopvil** [comment]
> thxs for the history lesson...but...2 years of BUG means that they maybe abbandoned this search plug ins project BUT up to now **more then 2 years later** there is really **NO replace project at all** and this is **a real SHAME**

nigga this is just what i said. It's a real shame and all that, because the project seems abandoned.

**Comment by p060477** [comment]
why no any word by devs...??...
no able to write a word on this BUG...??

**Comment by p060477** [comment]
> > thxs for the history lesson...but...2 years of BUG means that they maybe abbandoned this search plug ins project BUT up to now **more then 2 years later** there is really **NO replace project at all** and this is **a real SHAME**
> 
> nigga this is just what i said. It's a real shame and all that, because the project seems abandoned.

...nigga...??...i'm really not yr sister...or mother...or daughter.....
;)

**Comment by r1k0** [comment]
> I have not the slightest idea why, but updating to the latest version of the "cpasbien" unofficial plugin magically made search work again after getting the exact same errors. Found here: https://github.com/MarcBresson/cpasbien

this worked for me.

Simply manually add this plugin https://github.com/MarcBresson/cpasbien/blob/master/src/cpasbien.py
and they all got restored... no clue what's going on here. I'm running MacOS + 4.6.2 + py311

**Comment by p060477** [comment]
you are very very lucky aren't you...??

**Comment by godzfire** [comment]
I created an issue in the main program github since it seems no one is doing anything about this and we're completely dead until then.

**Comment by sledgehammer999** [comment]
For all people facing problems: The `searchplugins.qbittorrent.org` subodmain has been reworked in the last ~36 hours for the redirects. Can you click "Check for updates" in the search plugin manager? It should work for all people now (hopefully).

**Comment by godzfire** [comment]
> For all people facing problems: The `searchplugins.qbittorrent.org` subodmain has been reworked in the last ~36 hours for the redirects. Can you click "Check for updates" in the search plugin manager? It should work for all people now (hopefully).

I've been trying all day today. No dice.

**Comment by r1k0** [comment]
> Not an idea solution but heres a few torrent search sites to help until or IF this issue is fixed
> 
> https://solidtorrents.to/
> 
> https://www.limetorrents.lol/home
> 
> https://www.torrentdownload.info/
> 
> https://yourbittorrent.com/

this issue led me to install and use **jackett** - best search torrent I've seen and has many more sites, I wish qB would use it instead of individual python scripts
https://github.com/Jackett/Jackett (while pending your resolution)

**Comment by alessandro-ooo** [comment]
Hey, half a year ago I've uploaded all the search engines available in this repository in my own github, 1 download to get them all. 

Just in case someone needs them again, ima leave this link here since y'all are having issues with them plugins.
https://github.com/alessandro-ooo/one-click-qbittorrent-searchplugins

**Comment by ngosang** [comment]
Dev here. I just tested all the official plugins and they are working. I'm not very active in this project and I can't fix the issues I can't reproduce.

Windows:
* Python 3.10.11
* qBittorrent 4.6.3

Linux:
* Python 3.11.6
* qBittorrent 4.6.2

**Comment by Pocokk** [comment]
> Hey, half a year ago I've uploaded all the search engines available in this repository in my own github, because I think it's easier to download them all in 1 click, not copy the link and paste it in the browser for each plugin, 1 download to get them all.
> 
> Just in case someone needs them again, ima leave this link here since y'all are having issues with them plugins. https://github.com/alessandro-ooo/one-click-qbittorrent-searchplugins

Was it ever revisited whether or not all of them are working?

**Comment by olegkostoglotov** [comment]
I had to turn off certificate verification inside `nova3/helpers.py` to get search working on Windows again. 
See https://github.com/qbittorrent/qBittorrent/issues/20104#issuecomment-2119351100

**Comment by godzfire** [comment]
*bump* plugins still aren't working properly

**Comment by torinfin** [comment]
this just happened to me!  is there a known reason why this happens?  I'm not sure what the best way to fix is, theres several different instructions on how people fixed it.  
should python be fully removed then installed and then reinstall the plugins?

**Comment by cm-legend** [comment]
Same issue happened to me on macOS found the problem to be SSL: CERTIFICATE_VERIFY_FAILED, to correct this it was necessary to run the Python script as follows. Install Certificates: If you're on macOS, and using the default Python installation, the issue might be that Python is not using the system's certificate store. You can install the certificates by running the Install Certificates.command script found in your Python installation directory (usually /Applications/Python <version>/). This script installs the root certificates and should resolve the SSL error.

**Comment by ocvb** [comment]
> Same issue happened to me on macOS found the problem to be SSL: CERTIFICATE_VERIFY_FAILED, to correct this it was necessary to run the Python script as follows. Install Certificates: If you're on macOS, and using the default Python installation, the issue might be that Python is not using the system's certificate store. You can install the certificates by running the Install Certificates.command script found in your Python installation directory (usually /Applications/Python /). This script installs the root certificates and should resolve the SSL error.

Yeah you are right. Seems like my python previously installed manually left some files in `/Applications` qbittorrent found it and use that old installation than my current python, that are installed thru `brew`. In this case i had to point to `/opt/homebrew/bin/python3` executable.
