### ISSUE TITLE
Plugin maintainer doesn't respond, update wiki with fork

### ISSUE THREAD

**Issue by akaleeroy** [qbittorrent/search-plugins#27]
Plugin maintainer for [private site](https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins#plugins-for-private-sites) Filelist.ro, @adrianmocan, isn't responding, possibly due to health issues :cry: 

I made [a fix a while ago](https://github.com/adrianmocan/qbittorrent_plugin_filelist.ro/pulls) for the plugin and would like to update the wiki here with it. Is that OK?

**Comment by Chocobo1** [comment]
>Is that OK?

No need to ask for permission as long as you follow the rules ;)
From https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins#read-first:
>If you experience issues with any of the plugins posted here, please report to the author directly.
In case the author is unresponsive, you can try to fix it yourself. Then you can edit this wiki page and update the link to your fixed plugin.
