### ISSUE TITLE
wiki/Unofficial-search-plugins page not found

### ISSUE THREAD

**Issue by niamotullah** [qbittorrent/search-plugins#294]
i clicked on edit to see the source of a wiki page and then clicked on `delete page` because i couldn't find anything says undo or exit without saving changes. now i can't goto that page again
Page:  https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins

**Comment by stinky73** [comment]
Me too! Link in bittorrent https://plugins.qbittorrent.org now re-directs to https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins when clicked....

**Comment by if-ai** [comment]
https://github.com/qbittorrent/search-plugins/issues/121

**Comment by xavier2k6** [comment]
@Chocobo1 Looks like the page is after being deleted!!

**Comment by stinky73** [comment]
> #121

@if-ai thx! looking into installing Jackett now!

**Comment by Chocobo1** [comment]
>@Chocobo1 Looks like the page is after being deleted!!

I restored it.

@niamotullah 
Just don't click `delete page` and be careful next time.

**Comment by xavier2k6** [comment]
@Chocobo1 This is after happening again!!

**Comment by Chocobo1** [comment]
@xavier2k6 
I suppose you know how to remove git commits. Then you can just clone this: https://github.com/qbittorrent/search-plugins.wiki.git
Remove the commit that delete the page (and all commits that comes after) and force push. This will roll back the history.

BTW, do you think we should move the wiki into the repo? just like what we have done with the main wiki?

**Comment by xavier2k6** [comment]
>https://github.com/qbittorrent/search-plugins.wiki.git

Getting a 404 on that link?!

>BTW, do you think we should move the wiki into the repo? just like what we have done with the main wiki?

Most definitely, so as to stop issues like this happening again....might even be of no harm to have some form of CI testing for the unofficial plugins..

**Comment by Chocobo1** [comment]
>Getting a 404 on that link?! if I just navigate to it

I can clone it by using the `git` command line program.

>cloning fails in github desktop when I try to choose clone repo with URL

Strange that they don't even support their own URL.

>Most definitely, so as to stop issues like this happening again....

I don't have a concrete plan yet. I'll look into it in my free time.

>might even be of no harm to have some form of CI testing for the unofficial plugins..

Since we can't control unofficial plugins they might abuse the CI? I'll think about it later.
