### ISSUE TITLE
elitetorrent do not work

### ISSUE THREAD

**Issue by carolinaantes** [qbittorrent/search-plugins#304]
these do not work

**Comment by thalieht** [comment]
https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins

>**If you experience issues with any of the plugins posted here, please report to the author directly.**

**Comment by carolinaantes** [comment]
I have spoken with the author and if he adds elitetorrent but in my version of qbittorrent the 4.6.3 I give to add and nothing, someone who has a version similar to mine can test it.

**Comment by 444995** [comment]
> I have spoken with the author and if he adds elitetorrent but in my version of qbittorrent the 4.6.3 I give to add and nothing, someone who has a version similar to mine can test it.

Well, first off the elitetorrent script doesn't even work to begin with - it doesn't find any of the search results. Also, it looks like Elitetorrent has now gotten some kind of protection, so it may or may not be possible to make a plugin for the site. I haven't looked into it, only seen that they have implemented it, but I'll look at it tomorrow.

**Comment by carolinaantes** [comment]
sorry, I got confused with dontorrent, can you check if your version allows you to add it?

**Comment by carolinaantes** [comment]
I have spoken to the author and he is trying to fix it and any help is welcome.

**Comment by carolinaantes** [comment]
El autor lo acaba de arreglar! probarlo y comentar si veis algún fallo para avisarle.

**Comment by iordic** [comment]
> > I have spoken with the author and if he adds elitetorrent but in my version of qbittorrent the 4.6.3 I give to add and nothing, someone who has a version similar to mine can test it.
> 
> Well, first off the elitetorrent script doesn't even work to begin with - it doesn't find any of the search results. Also, it looks like Elitetorrent has now gotten some kind of protection, so it may or may not be possible to make a plugin for the site. I haven't looked into it, only seen that they have implemented it, but I'll look at it tomorrow.

The protection was a simple base64 (4 iterations) + rot13 encoding. Maybe in the future they improve it. But for the moment it's fixed at: https://github.com/iordic/qbittorrent-search-plugins/pull/5

**Comment by carolinaantes** [comment]
cuando decía que no se me instalaba me refería a dontorrent , ya lo he puesto en otro mensaje
