### ISSUE TITLE
with vers 5.0 portable all search plugins are disappeared

### ISSUE THREAD

**Issue by p060477** [qbittorrent/search-plugins#309]
win 10 home 64
qbittorrent ver 5.,0 portable as per:
https://github.com/qbittorrent/qBittorrent/wiki/How-to-use-portable-mode
unable to load any plugin official or non official
always get: "extension not supported"

i attach some part of the log:

[log .docx](https://github.com/user-attachments/files/17216252/log.docx)

hope this helps
thxs in adv 
cheers

**Comment by 444995** [comment]
There are already issues open about this exact problem, please check already opened issues before you make a new issue

**Comment by xavier2k6** [comment]
@p060477 it seems from the logs provided that at least python 3.8 is detected/prompted to update plugins as obsolete.

Did you do this & then close/re-open qBittorrent?

**Comment by p060477** [comment]
hi first so many thxs in adv:
at the very beginning of my log attached is written:
" Trovato eseguibile Python. 
Nome: "python". 
Versione: "3.8.10"
this means that i've python vers 3.8.10
[log.docx](https://github.com/user-attachments/files/17221209/log.docx)

**Comment by xavier2k6** [comment]
Did you update the plugins??

Can you provide your actual nova3 folder & proper logs please?

**Comment by xavier2k6** [comment]
>i've also python on my pc but is also it no installed but -portable-

>consider that i really do not want to install or qbvittorent or python..i have them in portable way and alweays working up to few days ago

https://github.com/qbittorrent/search-plugins/issues/227#issue-1602851640

We need more to go on here.......

screenshots/screengrab etc.

**Comment by p060477** [comment]
> Did you update the plugins??
> 
> Can you provide your actual nova3 folder & proper logs please?

yes of course...is clearly written in the log i've attached...:

`(I) 2024-10-01T21:45:22 - Il plugin "eztv" è obsoleto - aggiornamento alla versione 1.16
(I) 2024-10-01T21:45:22 - Il plugin "jackett" è obsoleto - aggiornamento alla versione 4.0
(I) 2024-10-01T21:45:22 - Il plugin "limetorrents" è obsoleto - aggiornamento alla versione 4.7
(I) 2024-10-01T21:45:22 - Il plugin "piratebay" è obsoleto - aggiornamento alla versione 3.3
(I) 2024-10-01T21:45:22 - Il plugin "solidtorrents" è obsoleto - aggiornamento alla versione 2.3
(I) 2024-10-01T21:45:22 - Il plugin "torlock" è obsoleto - aggiornamento alla versione 2.23
(I) 2024-10-01T21:45:22 - Il plugin "torrentproject" è obsoleto - aggiornamento alla versione 1.4
(I) 2024-10-01T21:45:22 - Il plugin "torrentscsv" è obsoleto - aggiornamento alla versione 1.4
(I) 2024-10-01T21:45:22 - Plugin torrentscsv non supportato.
(I) 2024-10-01T21:45:22 - Plugin torlock non supportato.
(I) 2024-10-01T21:45:22 - Plugin limetorrents non supportato.
(I) 2024-10-01T21:45:23 - Plugin eztv non supportato.
(I) 2024-10-01T21:45:23 - Plugin jackett non supportato.
(I) 2024-10-01T21:45:23 - Plugin piratebay non supportato.
(I) 2024-10-01T21:45:23 - Plugin solidtorrents non supportato.
(I) 2024-10-01T21:45:23 - Plugin torrentproject non supportato`

and my nova3 has only the folder engines and it is -empty-
this is the screenshoot:

![nova3 folder](https://github.com/user-attachments/assets/ac171e9a-15b7-4d56-b107-6eae907f7fcb)

and this is what happens when try to update search plugin:

![tryin updating plugins](https://github.com/user-attachments/assets/5a043692-9114-41f0-a5ae-5dcb94cc3a56)


and here it is latest log...:

[qbittorrent.log](https://github.com/user-attachments/files/17229841/qbittorrent.log)


any ideas...??!!!...
anyway thxs for yr kind attn
cheers

**Comment by xavier2k6** [comment]
@p060477 What's in the nova3 folder?? obviously there's the engines folder...but what else? can you upload the full contents, please? have you tried with the latest python version 3.12.7? also where have you obtained the portable version of python?

**Comment by p060477** [comment]
hi and first thx
1) you himself indicate:https://github.com/qbittorrent/qBittorrent/wiki/How-to-use-portable-mode
2) here it is the nova3 full contents:
![nova3 folder inside](https://github.com/user-attachments/assets/b42eb51e-f788-4726-9fdd-7ef95ed85b14)

**Comment by xavier2k6** [comment]
>where have you obtained the portable version of python?

I know, I told you how to install portable version of qBittorrent.

Please upload the `nova3` folder/all it's contents from the 4.6.7 version which worked & the 5.0.0 that doesn't work.

I want the actual files/folders......not screenshots of them.

**Comment by xavier2k6** [comment]
the *.py files aren't being recognized/associated with python.

**Comment by p060477** [comment]
hi and thxs
how to..??...pls indicate me in which way i should be able to upload the 2 folders phisically in their entirety...
thxs again:
cause dgra drop not worked here..:"We don’t support that file type."...this is the reply..:(

**Comment by xavier2k6** [comment]
put them in to *.zip files

**Comment by xavier2k6** [comment]
The python 3.8.10 version.....was this from portableapps?

**Comment by p060477** [comment]
here there are..:
[Uploading ver 4.6.7 nova3.zip…]()
[vers 5.0 nova3.zip](https://github.com/user-attachments/files/17232227/vers.5.0.nova3.zip)

**Comment by p060477** [comment]
here it is the new upload,sorry if i make mistakes..:
[vers 4.6.7nova3.zip](https://github.com/user-attachments/files/17232346/vers.4.6.7nova3.zip)
no python 3.8.10 was not from portable apps i have a tool:universal extractor that is able to portaliza lots of progs.
thxs for yr attn
cheers

**Comment by xavier2k6** [comment]
portable version of python may be the problem......can you try newer version......latest is 3.12.7

**Comment by mirco982** [comment]
What about macOS users?? Any advice?

**Comment by xavier2k6** [comment]
> What about macOS users?? Any advice?

macOS support for qBittorrent is minimal at this stage.....

update python to latest, remove any failing (even intermittently) unofficial plugins....some plugins on macOS required to actually select a category rather than "all"

ensure any plugins are downloaded correctly/up-to-date.

**Comment by p060477** [comment]
> portable version of python may be the problem......can you try newer version......latest is 3.12.7

where may i be able to find it "portable"...??...and in which path yr latest vers 5 portable should be able to use it...??
thxs so much in adv
cheers

**Comment by xavier2k6** [comment]
@p060477 ok, you mentioned previously that you were using a portable version of python........in any case can you download the latest version of python...https://www.python.org/ftp/python/3.12.7/python-3.12.7-amd64.exe

**Comment by p060477** [comment]
so where to put the newest python, i've already portabilized it with uniextractor....
thx again
cheers

**Comment by xavier2k6** [comment]
@p060477 please....just install python normally!! not some portable version of it!

We can take it from there then.....I don't know where you're putting files/what you're modifying etc. so will be very difficult to diagnose/aid you.

**Comment by xavier2k6** [comment]
You are running qBittorrent in portable mode but then also running a python version in portable mode too or some Frankenstein iteration of it.

**Comment by xavier2k6** [comment]
Have you tried setting the path to your portable python version in advanced options?

Also, some unofficial plugins are having issues/require updating by their authors or may need to be manually removed.

**Comment by p060477** [comment]
dear xavier2k6 yes THAT WAS THE SOLUTION!!
https://github.com/qbittorrent/search-plugins/issues/307#issuecomment-2389572562
Pogman was the genius!
thxs so much to all of you from the very deep of my poor heart
cheers!
:)
