### ISSUE TITLE
how to add this search plugin...??

### ISSUE THREAD

**Issue by p060477** [qbittorrent/search-plugins#311]
[nova3/engines/pornrips.py](https://github.com/qbittorrent/search-plugins/pull/310/files#diff-8ab99032e2626bc83d150cda9c66c52d22de732395321abf96e93cc4c7f37f82)

**Comment by xavier2k6** [comment]
https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins

**Comment by p060477** [comment]
so many thxs in adv
is possible with latest 5.00
not in prev 4.6.7
maybe due to the different pytrhon 3.8.10 against 3.12.......

**Comment by xavier2k6** [comment]
>not in prev 4.6.7

I could install it in both....I have python 3.12 on my machine, haven't tested with any lower python......

Try to always have/use the latest python version & disregard any older version if no longer in use & ensure you use the python path setting option in advanced settings that was added in v5.0.0

**Comment by p060477** [comment]
that option in Qbit adv is a treasure!...let us have many portable vers of qbittornt and of python
...whata a pity that the prev. 4.6.7 hasn't it......so in this way is better to have some python version to test cause maybe some searchplugins may not be compatible with a particular python vers
many thxs again to you and pogman
and to devel who has implemented this adv opt in vers 5.0 of course!!
cheers
