### ISSUE TITLE
problems with vers 5.0.0 and search plugin bt4g

### ISSUE THREAD

**Issue by p060477** [qbittorrent/search-plugins#312]
hi if i find something on this server https://bt4g.org so using the plug in bt4g i'm not able double clickin on the file to add it to the downloads...i've materially to go in the web at that add https://bt4g.org
and search for the file and then add it or with magnet link or with torrent link...is a particular issue between ver 5.0 and this plug in bt4g...??
thxs so much in adv
cheers

**Comment by xavier2k6** [comment]
the bt4g plugin was removed previously & has been replaced with [bt4gprx](https://raw.githubusercontent.com/TuckerWarlock/qbittorrent-search-plugins/main/bt4gprx.com/bt4gprx.py)

**Comment by p060477** [comment]
many thxs for yr kind attention and patience too...
cheers

**Comment by xavier2k6** [comment]
@p060477 If that plugin works for you, please close ticket.

**Comment by p060477** [comment]
it works for me so i thxs you very much and close the issue
