### ISSUE TITLE
Some search plugins show incorrect size

### ISSUE THREAD

**Issue by key-sir2329** [qbittorrent/search-plugins#315]
Hello, recently I've noticed that some search plugins no longer show the correct size of the torrent, it seems to truncate the size, for example something that is 27GiB will show as 27B. The following plugins are affected:

therarbg
torrentdownloadspro

Other search plugins like bitsearch and 1337x still function properly.

**Comment by thalieht** [comment]
>Other search plugins like bitsearch and 1337x still function properly.

Which means that this is a plugin problem. These are not official plugins so report this to their corresponding repo.

**Comment by key-sir2329** [comment]
I opened an issue here with a patch:
https://github.com/BurningMop/qBittorrent-Search-Plugins/issues/16
