### ISSUE TITLE
list not working

### ISSUE THREAD

**Issue by pikutiro** [qbittorrent/search-plugins#317]
did someone deleted the trackers py list? not working here anymore

**Comment by xavier2k6** [comment]
> did someone deleted the trackers py list? not working here anymore

Looks that way & it's not the first time a user has done this, it will be re-stored asap, measures will be put in place to prevent this type of thing again soon too.

**Comment by pikutiro** [comment]
That s nice! Thank you for the reply! Congrats for this great work

**Comment by xavier2k6** [comment]
back up & running.

**Comment by pikutiro** [comment]
Still missing the RUtracker one tought (the one I use most lol) ..... great too see it running again thanks
