### ISSUE TITLE
Issue installing new Search Plugin

### ISSUE THREAD

**Issue by nindogo** [qbittorrent/search-plugins#32]
I wrote [this](https://github.com/nindogo/qbtSearchScripts/raw/master/eztv.py) plugin but I can not be able to install it into qBittorrent.

Is there something I must do to get it to install?

**Comment by Chocobo1** [comment]
You defined `url` & `name` as class variable where as they should be class static variables... 
You should follow the code layout in https://github.com/qbittorrent/search-plugins/wiki/How-to-write-a-search-plugin for less surprises.
