### ISSUE TITLE
Plugins List is gone

### ISSUE THREAD

**Issue by Amogh1001** [qbittorrent/search-plugins#326]
Someone deleted the plugins page
![Screenshot_20241223_222052](https://github.com/user-attachments/assets/9967b1b5-17eb-4ad4-8a59-ce98bb0ed1bf)

**Comment by Amogh1001** [comment]
I wasn't sure on what to do, so I tried seeing if I could add an entry. Anyway, I checked on the wayback machine and it seems to be all there(?)

**Comment by lordmage** [comment]
for those lost the link here worked for me https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins-wiki.git#plugins-for-public-sites

**Comment by Amogh1001** [comment]
> for those lost the link here worked for me https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins-wiki.git#plugins-for-public-sites

Ah okay, thanks. Do I keep the issue up until it's fixed or should I close it?

**Comment by lordmage** [comment]
> > for those lost the link here worked for me https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins-wiki.git#plugins-for-public-sites
> 
> Ah okay, thanks. Do I keep the issue up until it's fixed or should I close it?

i did edit the link into your created page id leave the ticket open just for clarity sake and some one can properly restore the links and other pages if also affected

**Comment by stalkerok** [comment]
@Chocobo1 It's time to ban page editing.

**Comment by Amogh1001** [comment]
> > > for those lost the link here worked for me https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins-wiki.git#plugins-for-public-sites
> > 
> > Ah okay, thanks. Do I keep the issue up until it's fixed or should I close it?
> 
> i did edit the link into your created page id leave the ticket open just for clarity sake and some one can properly restore the links and other pages if also affected 

Yeah, that's what I was thinking too

**Comment by Chocobo1** [comment]
I've restored the wiki.
And from now on, the wiki pages are stored in the repo and under this directory: https://github.com/qbittorrent/search-plugins/tree/master/wiki
That means to make any changes, a pull request is mandatory.

@xavier2k6 FYI.

**Comment by Amogh1001** [comment]
> I've restored the wiki. And from now on, the wiki pages are stored in the repo and under this directory: https://github.com/qbittorrent/search-plugins/tree/master/wiki That means to make any changes, a pull request is mandatory.
> 
> @xavier2k6 FYI.

Thanks!
