### ISSUE TITLE
helper_functions requests

### ISSUE THREAD

**Issue by nindogo** [qbittorrent/search-plugins#33]
Hi,

is there an equivalent for `download_files` for magnet links; alternatively if it is possible please advise on how to use the current helpers to provide magnet_links

**Comment by Chocobo1** [comment]
From https://github.com/qbittorrent/search-plugins/wiki/How-to-write-a-search-plugin :
>link => A string corresponding the the download link (the .torrent file or magnet link)

**Comment by nindogo** [comment]
You are right on this - and I have used each (and in one case both) of this for a parser I have written

But:
take a website that has got it's magnet/.torrent link inside a second page (not in the search page). It may be necessary for speed (good user experience) to show all the information on the first page and only to go into the second page when the user asks for it.

In that case you have the option of using `download_files` for .torrents but no option for magnet links. This is the request I was making please.

**Comment by Chocobo1** [comment]
>In that case you have the option of using download_files for .torrents but no option for magnet links. This is the request I was making please.

With .torrent files it is likely to fetch it successfully over http (and in a timely manner), while with magnets, one have to fetch it from DHT which is prone to wait on forever & takes more resources for doing so.
While it is possible to implement in qbt but regarding search-plugin as no more than a side-project/sub-system I doubt it will ever be done (at least for now).

**Comment by nindogo** [comment]
OK. Completely get that it may not be a priority.

Thanks for responding.

**Comment by ngosang** [comment]
@nindogo I fixed it with a hack.

Take a look at https://github.com/ngosang/qBittorrent-plugins/blob/master/sumotorrent/sumotorrent.py#L63
I'm returning `magnet_link (space) original_url`

Please, if that solves your your problem close the issue.

**Comment by nindogo** [comment]
Hmm,

I will try this.

Thanks

**Comment by nindogo** [comment]
@ngosang I have tried this but it does not work for me.

I can see it working in your script but there may be something I am not seeing.

**Comment by nindogo** [comment]
https://github.com/nindogo/qbtSearchScripts/blob/master/uniondht.py

**Comment by ngosang** [comment]
You don't need to implement `download_torrent` or get the magnet link in uniondht. :disappointed: 
Yo can get the torrent directly from the torrent list.
Just use the code I fixed for you, is working fine => https://github.com/nindogo/qbtSearchScripts/pull/3

**1 example:**
In https://1337x.to/search/westworld/1/ you can't get the torrent nor magnet link from the torrent list, so, I return the description page as the download link.
When the user click download in qBittorrent, qBittorrent call the function `download_torrent` with the description link and I can extract the torrent/magnet from that page.
https://github.com/qbittorrent/search-plugins/blob/master/nova/engines/leetx.py

**Comment by MaurizioRicci** [comment]
Does anybody can understand why my download_file doesn't work in qBittorrent? 

Testing with "python nova2dl.py http://www.mejortorrent.org http://www.mejortorrent.org/peli-descargar-torrent-19914-Sueno-en-otro-idioma.html" works fine. 

And prints out: "C:\Users\Maurizio\AppData\Local\Temp\tmpmsayyec3 http://www.mejortorrent.org/uploads/torrents/tmp/torrent.php?table=peliculas/&name=Sueno_en_otro_Idioma_Hdrip_Latino.torrent"

Anyway it looks like qBt doesn't even call my function. The code is here: https://github.com/MaurizioRicci/qBittorrent_search_engine/blob/master/mejor.py

**Comment by MaurizioRicci** [comment]
I also tried to hardcode the download_file func, just for testing. So i write:
def download_torrent(self, info):
        print(download_file('http://www.mejortorrent.org/uploads/torrents/tmp/torrent.php?table=peliculas/&name=Como filmar una XXX3,39gb.torrent'))

But again qBt does absolutely nothing when i click the download button

**Comment by ngosang** [comment]
@MaurizioRicci The `download_torrent` function is perfect.
The bug is here https://github.com/MaurizioRicci/qBittorrent_search_engine/blob/master/mejor.py#L24
Replace `'MejorTorrent'` with `'http://www.mejortorrent.org'`

**Comment by MaurizioRicci** [comment]
@ngosang Thank you very much, now it works!! I updated my plugins: IlCorsaroNero and Mejor Torrent. Now download works properly.
