### ISSUE TITLE
Issue with new engine - not working uniondht.py

### ISSUE THREAD

**Issue by nindogo** [qbittorrent/search-plugins#34]
Hi,

I have made [this search](https://github.com/nindogo/qbtSearchScripts/raw/master/uniondht.py) plugin.

- The page has a bad certificate and also it uses cp1251. It also makes the torrent an attachment rather than inline.
- I saw that retrieve_url() did not handle the fonts well so I wrote my own for this. (The character encoding is recorded in the html meta not in the http headers.
- Same thing with prettyprinter() functionality - I emulated it's functioning as far as I could (save in a temporary file and print it and the desc_link to the terminal.
- Thing is no matter what I do - qBittorrent does not then load the .torrent file. 
Could you please assist me and look at what I may have done wrong.

**Comment by ngosang** [comment]
@nindogo fixed in https://github.com/nindogo/qbtSearchScripts/pull/3
