### ISSUE TITLE
Include new search plugins as official

### ISSUE THREAD

**Issue by ngosang** [qbittorrent/search-plugins#38]
After removing torrentz2 and demonoid, we have few official plugins.
I don't have much free time as I had in the past but I can review and merge small PRs.

The following sites are very popular, secure and **stable** so hopefully we don't have to update the plugins very often:
* RARBG https://github.com/b0nk/qbittorrent-search-plugins/issues/6
* 1337x https://github.com/nindogo/qbtSearchScripts/issues/2 https://github.com/v1k45/1337x-qBittorrent-search-plugin/issues/6
* EZTV https://github.com/nindogo/qbtSearchScripts/issues/1

I know @v1k45 is the original author for 1337x plugin and @nindogo forked it. I don't know who is more active so I asked both, please don't open 2 PRs :smile: 

@Chocobo1 @b0nk @nindogo @v1k45

**Comment by nindogo** [comment]
Hi,

If it is ok with @v1k45 go on and use it.

Ni

**Comment by b0nk** [comment]
Hi.

Like I said in my repository there are a few things that I believe need your attention before adding it.

* The script does NOT parse the rarbg website.
* It is dependent on torrentapi.org which I DO NOT own or control.
* And even that is dependent on a ruby plugin that I DO NOT own.

If you think this is nothing to worry about I have no problem staying as maintainer of the plugin in the forseeable future and you can go ahead and make a PR.

Cheers and keep up the FOSS effort!

**Comment by ngosang** [comment]
> It is dependent on torrentapi.org which I DO NOT own or control.

It's safe, it's used by several software like [medusa](https://github.com/pymedusa/Medusa/blob/master/medusa/providers/torrent/json/rarbg.py), Jackett...

RARBG => https://github.com/qbittorrent/search-plugins/pull/48

**Comment by ngosang** [comment]
The 3 plugins are official now. Just click 'check for update' in qBittorrent.
