### ISSUE TITLE
Remove malicious site kickass-cr.online

### ISSUE THREAD

**Issue by LuBega5** [qbittorrent/search-plugins#49]
This site is malicious, please remove its search engine from the unofficial plugins list.
The "Direct download" button, most of the time, will simply lead to a commercial partner site, which is not the problem. But sometimes it will open a download window for a (presumably malicious) .exe file (and this even if the torrent content is not an .exe file).

**Comment by MaurizioRicci** [comment]
I wrote that plugin, and I used it to download some stuff. Could you please give more information on the problem? It is tested and description link and download should be fine. Maybe you encountered in some particular page? Please give more detail

**Comment by LuBega5** [comment]
The problem is not about the qbittorrent search plugin that you wrote, it's about the web site. The problem I described happens  when one clicks on the _"Direct download"_ button _on the web site_. This is what happens (maybe 10-20% of times):

![screenshot](https://user-images.githubusercontent.com/43374607/45720867-2b497600-bba6-11e8-891b-e5cf35e71611.png)

The site makes the user download an executable, which is most probably malware.
This is a malicious behavior from the site to infect unsuspecting users and thus in my opinion this site should not be recommended with a search plugin (unofficial or not).

**Comment by cubedj** [comment]
this has nothing to do with the search plugin and is absolutely up to you if you want to use this site - I wouldn't - at least without adblocker, still - search plugin works and can download only magnet links... btw don't use "direct download" buttons on any torrent site.. as a rule...

**Comment by LuBega5** [comment]
Ok I just tested that Zooqle does exactly the same thing with exactly the same domain... I didn't know it was that common. You can probably ignore my comment then...

**Comment by cubedj** [comment]
the stuff you do in your browser is here really off topic - but even if those sites have some malicious intentions still doesn't change anything about the fact that using the search plugin for that site is safe, the plugin simply parses the website and looks for magnet links and won't download anything else... your conclusion that you shouldn't trust qbittorrent search plugins from now on is wrong, theres no reason for that...

**Comment by MaurizioRicci** [comment]
I use adblocker and I didn't see any malicious files. I suggest that you use it too, it works well
