### ISSUE TITLE
snowfl fixing

### ISSUE THREAD

**Issue by Pireo** [qbittorrent/search-plugins#56]
@ngosang are you capable of fixing https://raw.githubusercontent.com/hannsen/qbittorrent_search_plugins/master/snowfl.py ?

**Comment by ngosang** [comment]
I don't have time. Maybe @MaurizioRicci

**Comment by gitDew** [comment]
I've went ahead and wrote a plugin for snowfl that should work now, apart from the download button. You can find the plugin [here](https://raw.githubusercontent.com/gitDew/qbittorrent-snowfl-search-plugin/master/snowfl.py), and the updated information in the wiki.

**Comment by Pireo** [comment]
@gitDew thanks a lot! The download button also works to me!

**Comment by ChocoTonic** [comment]
> I've went ahead and wrote a plugin for snowfl that should work now, apart from the download button. You can find the plugin [here](https://raw.githubusercontent.com/gitDew/qbittorrent-snowfl-search-plugin/master/snowfl.py), and the updated information in the wiki.

this is 404
update here:
https://github.com/qbittorrent/search-plugins/issues/435
