### ISSUE TITLE
Search results showing 0 seeders and 0 leechers across the board

### ISSUE THREAD

**Issue by kapamalo** [qbittorrent/search-plugins#57]
Please provide the following information:

qBittorrent version and Operating System:
V. 4.1.3 (64-bit), Mac OS High Sierra

What is the problem?
All searches result in 0 seeds, 0 leechers.

What is the expected behavior?
For popular downloads, should be getting hundreds of seeders, but all of my search results, for many different search strings, result in 0 seeders, 0 leechers.

Steps to reproduce:
qBittorrent was working fine. However, three separate things happened between when it worked and when it didn't. 1) I updated to v. 4.1.3. 2) I tried turning on FileVault, but then turned it off a few days later (don't ask me why, I guess I was just curious). 3) I tried turning on the built-in firewall, but then turned it off a few days later (Again, don't ask my why--shouldn't have experimented). I changed zero settings in either FileVault or Firewall settings. I have no idea which of these three things, or which combination of things, has caused my problem. Anyone have any idea where to look to see if something is blocking qBittorrent from communicating with seeders/leechers?

Log:
2018-10-06 7:09 PM - 'The Hobbit The Battle Of The Five Armies 2014 720p HDCAM FIRST ENG x264 Pimp4003' added to download list.
2018-10-06 7:09 PM - Download first and last piece first: Off, torrent: 'The Hobbit The Battle Of The Five Armies 2014 720p HDCAM FIRST ENG x264 Pimp4003'
2018-10-06 6:51 PM - Python found in PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
2018-10-06 6:51 PM - Python detected, version: 2.7.10

Snip:
![image](https://user-images.githubusercontent.com/43919099/46584133-19c8f080-ca25-11e8-984e-2add36010ed6.png)

**Comment by kapamalo** [comment]
I posted in another thread, and another user said they were showing the same, and suggested I post here.

**Comment by ngosang** [comment]
@kapamalo we are getting the seeds/peers from https://www.torlock.com/all/torrents/hobbit.html?sort=seeds&order=desc
seems there is a problem in that page...
If it's important for you, update the plugins and try another search engine.

**Comment by kapamalo** [comment]
Fixed. Sorry, I'm new to qTorrent. The solution was simply to update all the search engine plugins:
![image](https://user-images.githubusercontent.com/43919099/46585092-b1ccd700-ca31-11e8-826f-ff9266d4dc32.png)
