### ISSUE TITLE
Problems with Window gigantism

### ISSUE THREAD

**Issue by xzj8b3** [qbittorrent/search-plugins#58]
![schermata da 2018-10-28 11-28-14](https://user-images.githubusercontent.com/26720956/47617372-e7ac2b00-dac6-11e8-8447-02d3f21a361b.png)

Using the search field already from Fedora 28 The window comes out of the desktop on Monitor 1366x768 (16.9), the same problem is re-present on Fedora 29 hiding various buttons and options, please correct so that you can enjoy a correct use of the Software now unusable!!!!

**Comment by Chocobo1** [comment]
Hi xzj8b3, this is not the right place to report, please file an issue at:
https://github.com/qbittorrent/qBittorrent/issues
