### ISSUE TITLE
Sites which use cloudflare

### ISSUE THREAD

**Issue by Pireo** [qbittorrent/search-plugins#60]
Idope.site and Skytorrents.lol have this problem, @kernc and @NiNdogo

**Comment by kernc** [comment]
Besides currently not showing results for me, what's the problem, exactly?

**Comment by Pireo** [comment]
If you try to connect to the site, a cloudflare message appears first.

**Comment by ngosang** [comment]
It's very hard to bypass Cloudflare. Maybe they expose an API or Proxy without Cloudflare.

**Comment by kernc** [comment]
I would not be someone with any say for the core of qBittorrent. :smiley: But I have few ethical reservations; so what would the javascript code be?

**Comment by ngosang** [comment]
JS runtime and JS code will never be added to qBittorrent. You can use Jackett instead.

**Comment by nindogo** [comment]
> I would not be someone with any say for the core of qBittorrent. 😃 But I have few ethical reservations; so what would the javascript code be?

Something like [this](https://github.com/Anorov/cloudflare-scrape#cloudflare-scrape) could work.
