### ISSUE TITLE
Change tpb domain to .asia

### ISSUE THREAD

**Issue by Pireo** [qbittorrent/search-plugins#64]
@ngosang @Chocobo1 I recommend you to change the tpb domain to https://thepiratebay.asia/ 
ah, can you add linuxtracker as official? Also read this: https://torrentfreak.com/spooky-torrent-warns-eztv-users-about-huge-security-risk-180408/
Plus someone made a plugin for yts if you noticed, so we should include both or none imho.
I also wonder if it is possible to make zooqle categories working in the plugin.

**Comment by ngosang** [comment]
@Pireo Fixed the pirate bay in #70 The .asia domain is fake.

**Comment by ngosang** [comment]
YTS author doesn't respond so I assume we can't make it official.

Zooqle RSS feed is wrong so we have to redo the plugin again without RSS, it's too much work for me.

**Comment by ngosang** [comment]
@Pireo I contacted Zooqle owner. Maybe he fix it for us.
