### ISSUE TITLE
qBittorrent search not working (Mac OS 10.14.2)

### ISSUE THREAD

**Issue by gumpster2010** [qbittorrent/search-plugins#66]
I'm having issues getting any search results to show up.  I just upgraded to qBittorrent 4.1.5 and I installed a number of plugins.  When I enter my search criteria, nothing shows up (depending on which plugins I enable, it either sits there indefinitely with no results, or it goes quickly to the orange "no results" triangle).  

This issue persists whether or not I use a VPN.  And my qBittorrent preferences are pretty much defaults.  Other than this search issue, qBittorrent works fine. 

It's odd because when I actually go to the trackers' websites, the same searches yield plenty of results. 

I had similar issues with previous versions of 4.1... ever since I upgraded my Mac OS to Mojave I've had issues (even after uninstalling and reinstalling qBittorrent a number of times, even going back to old versions).

**Comment by ngosang** [comment]
We need more information. What is your Python version? Check it in the execution log.
![image](https://user-images.githubusercontent.com/10577978/51439437-67a6f300-1cba-11e9-8ee5-946108ecc298.png)

**Comment by gumpster2010** [comment]
Hi, thanks!  I had Python 3.6.7.  I just installed 3.7.2 and it seems to work better actually, so thanks for pointing that out.  (Of course most of the plugins don't seem to work, but that may just be a plugins issue)

**Comment by ngosang** [comment]
@gumpster2010 try Jackett ;)
