### ISSUE TITLE
Search plugins not working

### ISSUE THREAD

**Issue by gorvinsky** [qbittorrent/search-plugins#69]
I've been using a lot of search plugins for a long time. But today suddenly all of them are missing and whenever I try to install a plugin, it says it's incompatible.

**Comment by ngosang** [comment]
@gorvinsky Try to update to v4.1.5 and test again.

**Comment by gorvinsky** [comment]
> 
> 
> @gorvinsky Try to update to v4.1.5 and test again.

I am using v4.1.5 already as I create the issue.

**Comment by gorvinsky** [comment]
Latest update. Everything is working fine for now. I didn't change anything.

**Comment by avuman** [comment]
I'm still having this issue. One day I opened up the Search tab, and all of my old plugins were missing. Any solution?

**Comment by linuxwwarrior** [comment]
I just opened qbittorrent 4.1.7 in Ubuntu 18.04.2 and the other day all my plugins were there, but now I am having the same issue, all my search plugins are gone and I cant reinstall any, gives incompatible error.  Did anyone resolve this yet??

**Comment by thalieht** [comment]
https://github.com/qbittorrent/qBittorrent/issues/11149#issuecomment-530864855
