### ISSUE TITLE
Library "helpers" in Plugins for search engine

### ISSUE THREAD

**Issue by lucgiffon** [qbittorrent/search-plugins#7]
Hello,

I'm trying to install https://raw.githubusercontent.com/ebukari/qbittorrent-plugins/master/kickass.py but it doesn't work on my side. I've tested the code with the provided "main" and I noticed I lack one library called "helpers".
```

wolfgang@everest:~/Downloads$ python3 kickass.py 
Traceback (most recent call last):
  File "kickass.py", line 11, in <module>
    from helpers import retrieve_url
ModuleNotFoundError: No module named 'helpers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kickass.py", line 19, in <module>
    from helpers import retrieve_url
ModuleNotFoundError: No module named 'helpers'

```

What is this?

Thank you

**Comment by sledgehammer999** [comment]
From: https://github.com/qbittorrent/search-plugins/wiki/How-to-write-a-search-plugin#test-your-plugin

Go to your nova folder, copy the kickass.py inside `engines/` subfolder and then (outside of that subfolder)
```
./nova2.py Kickass all ubuntu

or

python3 nova2.py Kickass all ubuntu
```

**Comment by sledgehammer999** [comment]
I forgot to answer your specific question. "helpers" is bundled with nova/nova3.
