### ISSUE TITLE
Jackett plugin fails with "Search returned no results"

### ISSUE THREAD

**Issue by Nocifer** [qbittorrent/search-plugins#75]
OS: Arch Linux
Python: 3.7.2

I'm _really_ happy you've implemented this new Jackett search plugin (which I found completely by chance!) because now I can once more use qBittorent as a torrent search engine like I used to, but with the added power and versatility of Jackett (which I've been using for the past year or so). But unfortunately I can't get it to work properly: most of the times when I search for something, qBittorrent reports that the "Search returned no results".

Steps to reproduce:

0) Search queries tried: "resident evil", resident evil, resident.evil, "lion king", lion king, lion.king, "harry potter", harry potter, harry.potter

1) I first searched directly from within Jackett and obtained the following results (in all cases I left the category unspecified):
"resident evil": 524
resident evil: 693
resident.evil: 455
"lion king": 283
lion king: 443
lion.king: 382
"harry potter": 486
harry potter: 631
harry.potter: 508

2) Then I searched via terminal, by simply replacing line 130 `prettyPrinter(res)` of jackett.py with a standard `print(res)`, adding a loop counter to count the total results, and then running jackett.py on its own and feeding it strings via its main(). The results were exactly the same:
"resident evil": 524
resident evil: 693
resident.evil: 455
"lion king": 283
lion king: 443
lion.king: 382
"harry potter": 486
harry potter: 631
harry.potter: 508

3) Lastly, I searched from within qBittorrent. The results were dreadful:
"resident evil": 524
resident evil: Search returned no results
resident.evil: Search returned no results
"lion king": 283
lion king: Search returned no results
lion.king: 382
"harry potter": 486
harry potter: Search returned no results
harry.potter: Search returned no results

Unless I'm mistaken, this means that in all cases Jackett itself receives the query, understands it, processes it, and replies with a consistent number of results; which rules it out as it being the culprit. So I guess that whatever is responsible for breaking things probably lies somewhere within that prettyPrinter() function. Could it be an incompatibility with Python 3.7?

**Comment by mushnamukk** [comment]
https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin

**Comment by Nocifer** [comment]
Thanks for that link @mushnamukk. I've already configured the plugin properly so it wasn't really helpful, but it indirectly served as a starting point to discover what the real issue is.

So, it turns out there is this block in **jackett.py**, lines 109-118:

```
# process search results
response_json = json.loads(response)
for result in response_json['Results']:
    res = {
        'size': '%d B' % result['Size'],
        'seeds': result['Seeders'],
        'leech': result['Peers'],
        'engine_url': self.url,
        'desc_link': result['Comments']
    }
```
And also this block in **novaprinter.py**, lines 33-34 (inside the prettyPrinter method):

```
if 'desc_link' in dictionary:
    outtext = "|".join((outtext, dictionary["desc_link"]))
```

In the first block, the results from Jackett are parsed in order to populate the 'res' dictionary, which we then pass to prettyPrinter.

The issue lies in the fact that some torrent search engines return a NULL for the "Comments" section, which results in a **'desc_link': None** property for the 'res' dictionary, like e.g. with AniRena:
```
{'size': '11832635392 B', 'seeds': 0, 'leech': 0, 'engine_url': 'http://127.0.0.1:9117', 'desc_link': None, 'name': '[AniRena] Resident.Evil.Revelations.PS3-ALI213', 'link': 'magnet:?xt=urn:btih:f8fade39c492c8d0543011e2ac6540d33a046bf8&dn=Resident.Evil.Revelations.PS3-ALI213&tr=http%3A%2F%2Ftracker.anirena.com%3A80%2Fannounce&tr=http%3A%2F%2Fbt.ali213.net%3A8000%2Fannounce&tr=http%3A%2F%2Fbt.ali213.net%3A8080%2Fannounce&tr=http%3A%2F%2Fbt.ali213.net%3A5858%2Fannounce&tr=http%3A%2F%2Fopen.nyaatorrents.info%3A6544%2Fannounce&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80%2Fannounce'}
```
When this is passed to prettyPrinter, it tries to "join" this None value to a string and of course it fails, and so this happens:
```
❯ python ./jackett.py
Traceback (most recent call last):
  File "./jackett.py", line 163, in <module>
    jackett_se.search("resident evil", 'all')
  File "./jackett.py", line 131, in search
    prettyPrinter(res)
  File "/home/nocifer/.local/share/data/qBittorrent/nova3/engines/novaprinter.py", line 34, in prettyPrinter
    outtext = "|".join((outtext, dictionary["desc_link"]))
TypeError: sequence item 1: expected str instance, NoneType found
```
The obvious solution to this is to perform a simple check in order to determine whether res['desc_link'] has a None value, and if so replace it with an empty string (or whatever other valid value) before we perform the join. E.g.:
```
# process search results
response_json = json.loads(response)
for result in response_json['Results']:
    res = {
        'size': '%d B' % result['Size'],
        'seeds': result['Seeders'],
        'leech': result['Peers'],
        'engine_url': self.url,
        'desc_link': result['Comments']
    }

    # make sure desc_link is a string
    if res['desc_link'] is None:
        res['desc_link'] = ""
```
And that's it, problem solved.

**Comment by ngosang** [comment]
Fixed in #79, update the plugin

**Comment by ngosang** [comment]
@Nocifer If you find more errors, please, open more issues.

**Comment by twig123** [comment]
I believe this fix needs to be applied to the Python2 version of the plugin as well. Using Python2, I configure the json in the nova folder, and can see the search hitting Jackett, but returns "Search returned no results". Installing Python3 and configuring the json in the nova3 folder, and proper results are returned.

**Comment by ngosang** [comment]
I tested the Jackett plugin with Python 2.7.17 and it's working.
Anyway, I recommend to switch to Python3 => https://pythonclock.org/
