### ISSUE TITLE
Does this search-plugins need VPN？

### ISSUE THREAD

**Issue by chinaylssly** [qbittorrent/search-plugins#76]
see title，I am in china

**Comment by Nocifer** [comment]
Even though I'm not a qBittorrent developer, I'll venture a reply: yes, the searches are performed in exactly the same way as if you had performed them yourself via e.g. your browser, so if the torrent search engine you're trying to use is blocked in your country, then it will still be blocked when searching through qBittorrent. So yes, you will still need a VPN.

**Comment by ngosang** [comment]
@Nocifer answer is right.
