### ISSUE TITLE
Jackett plugin: using 'I' as string field separator in 'novaprinter.py' breaks search results

### ISSUE THREAD

**Issue by Nocifer** [qbittorrent/search-plugins#77]
I noticed this when performing a search with the Jackett plugin (see the first result):

![2019-02-19 14-56-39 qbittorrent v4 1 5](https://user-images.githubusercontent.com/6195422/53016649-c34dd300-3456-11e9-9df9-31eed5d12079.png)

I traced that result to this particular instance of the 'res' dictionary:
```
{'size': '19756849152 B', 'seeds': 0, 'leech': 0, 'engine_url': 'http://127.0.0.1:9117', 'desc_link': 'https://katcr.co/torrent/168823/resident-evil-7-biohazard-deluxe-edition-v-1-03-dlcs-2017-pc-repack-qoob.html', 'name': '[KickAssTorrent] Resident Evil 7: Biohazard - Deluxe Edition [v 1 03 + DLCs] (2017) PC | RePack от qoob', 'link': 'magnet:?xt=urn:btih:d8156cb400e50729b3a6e994683dd9a4395c0684&dn=Resident Evil 7: Biohazard - Deluxe Edition [v 1 03 + DLCs] (2017) PC | RePack от qoob&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://tracker.opentrackr.org:1337&tr=udp://tracker.pirateparty.gr:6969&tr=udp://9.rarbg.to:2710&tr=udp://9.rarbg.me:2710'}
```
...which is created in **jackett.py** by parsing Jackett's results and then is passed on to qBittorrent via the prettyPrinter() method residing in **novaprinter.py** (lines 30-32):
```
outtext = "|".join((dictionary["link"], dictionary["name"].replace("|", " "),
                        str(dictionary["size"]), str(dictionary["seeds"]),
                        str(dictionary["leech"]), dictionary["engine_url"]))
```
I believe the problem lies in the fact that this particular result utilizes the '|' character not only in its name but also in its magnet link, while at the same time '|' also serves as the field separator for the string prettyPrinter returns to qBittorrent's UI. While this could be "fixed" by applying a **.replace("|", " ")** also to the link part, just as it is applied to the "name" part, it would probably result in the magnet link not working anymore.

So, if my understanding of the issue is correct, I believe a proper solution would be to replace '|' with something more unique as the field separator.

**EDIT:** Turns out that the '|' character in the magnet link is only used in its "dn" field and not as part of the real link itself, so applying a **.replace("|", " ")** to it does indeed fix this issue.

**Comment by ngosang** [comment]
Fixed in #79, update the plugin
