### ISSUE TITLE
couldn't check for plugin updates

### ISSUE THREAD

**Issue by millerthegorilla** [qbittorrent/search-plugins#8]
qbittorrent is reporting when the update plugins button is pressed that the update server is unavailable.  This has been like this for a while.

on xubuntu 17.04

**Comment by sledgehammer999** [comment]
Wrong bug tracker. I also assume you use an old version of qbittorrent since you don't mention.
Use the most recent one from our PPA: https://launchpad.net/~qbittorrent-team/+archive/ubuntu/qbittorrent-stable

If that works, please report back and close this issue.
