### ISSUE TITLE
Jackett disabled

### ISSUE THREAD

**Issue by lacruzanthony** [qbittorrent/search-plugins#90]
Hello. I have a question about jackett plugin.

In the wiki tab says that I have to disable Jackett in order to use it, but I don't understand, if I want to use Jackett why I have to disable it?

And in the  Screenshot section shows Jackett as selected engine, so I don't get it.

Thanks!

**Comment by thalieht** [comment]
You got it wrong, it says that it's enabled by default and how to disable it if you don't want/use it.

**Comment by lacruzanthony** [comment]
Ok, thanks :)
