### ISSUE TITLE
"Jackett: api key error!"

### ISSUE THREAD

**Issue by AnthonyBe** [qbittorrent/search-plugins#91]
My Jackett search plugin just updated to v3.2 and I'm now getting an error as soon as I try and perform a search in qB:

"Jackett: api key error! Click 'Go to Description' button to open help."

Could possibly also be Jackett v0.11.316.0 as it updates daily on beta release but every beta has been reliable for me so I suspect the qB Jackett plugin more than Jackett itself.

qB v4.1.6 x64 on Windows 10
Jackett v0.11.316.0
python 3.7.3

**Comment by ngosang** [comment]
I tested it with the same versions and it's working.
Please, follow the installation guide:
https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin

**Comment by AnthonyBe** [comment]
I did follow the installation  guide.

It has been working perfectly until the 3.2 plugin update. I even reentered API into config file (there was no change).

Still broken.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by AnthonyBe** [comment]
If anyone can spot something I've missed to explain why it suddenly broke when I updated the qB Jackett Search plugin to 3.2 I'd really appreciate it!

My jackett.json file from C:\Users\Anthony\AppData\Local\qBittorrent\nova3\engines folder:
![image](https://user-images.githubusercontent.com/17214552/57564871-d9848300-73f6-11e9-87c0-c2a89fae71d2.png)

My Jackett UI with API Key:
![image](https://user-images.githubusercontent.com/17214552/57564883-f91bab80-73f6-11e9-8435-1ea512cfcfb8.png)

and my Jackett Config:
![image](https://user-images.githubusercontent.com/17214552/57564892-26685980-73f7-11e9-83a3-734f1a91a2ac.png)

**Comment by AnthonyBe** [comment]
OK, I've found the issue.

My machine has both python 2 and 3 installed on it.

qB had always been detecting python 3 in the execution log on start up, and thus when using the jackett search plugin, I had only ever needed to configure the jackett.json in the '### nova3/engines' folder.

As soon as I updated the jackett.json in the '### nova/engines' folder, it worked. When I then checked the qB execution.log, it was detecting python 2.7.16 for some reason, rather than defaulting to the python 3 install.

I had updated my python 2 and 3 installs to the latest point release in the last few weeks so I can only assume that the order of reference in my path statement has been switched and for some reason, it has taken a week or two to manifest into this problem!

**Comment by ngosang** [comment]
At the end of the year I want to drop python2 support, so I hope this problems disappear.

**Comment by kjp2006** [comment]
just checking up, I have this error as well and I was wondering if you got the python2 support possibly rolling in?

**Comment by ngosang** [comment]
I tested the Jackett plugin with Python 2.7.17 and it's working.
Anyway, I recommend to switch to Python3 => https://pythonclock.org/
