### ISSUE TITLE
Installing search plugin - python not detected

### ISSUE THREAD

**Issue by tsposato** [qbittorrent/search-plugins#93]
I'm trying to install any search plugin and the logs tell me the Python is not detected.
Python is installed and in path. I'm running 4.1.6 on FreeBSD (freenas plugin).
How does qbittorrent use python, so I need to symlink it somewhere for it to pick it up?

**Comment by tsposato** [comment]
Python exists at /usr/local/bin/python3.6
I have also created a symlink at /usr/local/bin/python
/bin and /sbin are read-only filesystems on a freenas plugin

**Comment by ngosang** [comment]
Try to open a console and type "python" and "which python". To see if it's in the env path, the version and the path.
Python detection is made in the qBittorrent core repository, not in this one. There are other related issues there #10658

**Comment by tsposato** [comment]
Here it is:
$ python -V
Python 3.6.8
$ which python
/usr/local/bin/python
$

**Comment by tsposato** [comment]
any ideas?

**Comment by ngosang** [comment]
@tsposato try to make a symbolic link and restart qBittorrent.
/usr/local/bin/python => /usr/bin/python

@Chocobo1 did you change the Python detection code in latest versions?

**Comment by tsposato** [comment]
> @tsposato try to make a symbolic link and restart qBittorrent.
> `/usr/bin/python`=> /usr/local/bin/python`
> 
This is something I can't do unfortunately. The FreeNAS ecosystem has these filesystems as read=only.

**Comment by foreachthing** [comment]
I got the exact same issue. Any news on how to fix this?

```
root@qbittorrent:/ # ln -s /usr/local/bin/python /usr/bin/python
ln: /usr/bin/python: Read-only file system
```

**Comment by ngosang** [comment]
I'm running out of ideas. You can try to run this command and then start qbittorrent.
`export PATH="$PATH:/usr/local/bin"`

You can do both in one line:
`export PATH="$PATH:/usr/local/bin" && qbittorrent`

**Comment by tsposato** [comment]
So, the startup script for this jail is in /etc/rc.local
I exported the PATH, did a restart and it successfully picks up python now.
I think this is more of an upstream qbittorrent plugin problem in freenas...

**Comment by foreachthing** [comment]
Ok ... I added the python path to the "export path" `set path=($path /usr/local/bin/python)` (for csh). Still no luck.
But I got some more lines from the log:
All of the plugins are _not_ supported! (I've shortened the log)

`(I) 2019-10-03T00:35:11 - Plugin jackett is not supported.

(I) 2019-10-03T00:35:11 - Python not detected
(I) 2019-10-03T00:35:11 - Plugin leetx is not supported.
(I) 2019-10-03T00:35:11 - Python not detected
(I) 2019-10-03T00:35:11 - Plugin rarbg is not supported.
(I) 2019-10-03T00:35:11 - Python not detected
(I) 2019-10-03T00:35:11 - Plugin torlock is not supported.
(I) 2019-10-03T00:35:11 - Python not detected
(I) 2019-10-03T00:35:11 - Plugin zooqle is not supported.
(W) 2019-10-03T00:35:45 -  is not a valid IP address and was rejected while applying the list of banned addresses.
(N) 2019-10-03T00:35:45 - Web UI translation for selected locale (en) has been successfully loaded.
(N) 2019-10-03T00:35:45 - Web UI: Now listening on IP: *, port: 8080
(W) 2019-10-03T00:39:11 -  is not a valid IP address and was rejected while applying the list of banned addresses.
(N) 2019-10-03T00:39:11 - Web UI: Now listening on IP: *, port: 8080
root@qbittorrent:~/.local/share/data/qBittorrent/logs #`

**Comment by tsposato** [comment]
Are you using FreeNAS plugin of qbittorrent or something else? Make sure the path you use is the one that returns from the command 'which python'.

You also need to do it in the script that is starting qbittorrent.

**Comment by ngosang** [comment]
@tsposato @foreachthing If this workaround fix the problem, please open an issue in freenas linking this issue so they can fix it for other users. I have no experience with freenas.

**Comment by NorthernMunkey** [comment]
> 
> 
> So, the startup script for this jail is in /etc/rc.local
> I exported the PATH, did a restart and it successfully picks up python now.
> I think this is more of an upstream qbittorrent plugin problem in freenas...

can you explain what you put in the rc.local please. i have the same issue with python not being found in my qbittorrent jail, if i do python -v it says python unknown, yet if i look in local/usr/bin python3 and 3.6 are there

**Comment by tsposato** [comment]
root@qbittorrent:~ # echo $PATH
/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
root@qbittorrent:~ # which python
/usr/local/bin/python
root@qbittorrent:~ # cat /etc/rc.local
export PATH="$PATH:/usr/bin:/usr/local/bin" && /usr/local/bin/qbittorrent-nox -d
root@qbittorrent:~ #

You might need to symlink python in PATH if it doesn't exist.
