### ISSUE TITLE
[Request] Search plugin for divxtotal

### ISSUE THREAD

**Issue by vermeko** [qbittorrent/search-plugins#95]
Could you write a search plugin for https://www.divxtotal3.net, please?

**Comment by ngosang** [comment]
It's supported in Jackett, it's a external software.
https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin

**Comment by macaju** [comment]
I have just configurated jackett but divxtotal is not there

**Comment by ngosang** [comment]
i see... try newpct, btbit, btdb...
