### ISSUE TITLE
btdb.eu lists fake size

### ISSUE THREAD

**Issue by Pireo** [qbittorrent/search-plugins#96]
I've noticed it lists GB as MB
@ngosang

**Comment by ngosang** [comment]
It's working well for me. Please give me an example.

**Comment by Pireo** [comment]
![Cattura](https://user-images.githubusercontent.com/6324108/59566904-868d9380-9066-11e9-99d5-44ad98db268d.PNG)

what's supposed to be a movie is just a fw KB, how's that possible?

**Comment by ngosang** [comment]
BTDB is a DHT indexer, so fake torrents can happen.
For me is 99.9% truth worthy. Now with the seeds & peers you can detect this fakes easy => #99
