### ISSUE TITLE
Attempt to Download new Plugins Doesn't save .py File to my PC!

### ISSUE THREAD

**Issue by BloodPriestess** [qbittorrent/search-plugins#98]
When I click on any download link, what happens instead is it loads the code behind that particular plugin and a web address that ended with the .py extension.

In the past, I tried just copying that web address into qbittorrent but found it kept coming up with errors. 

![Plugins](https://user-images.githubusercontent.com/34415506/59561306-8c2cae80-9051-11e9-8e1c-5e51703d5548.jpg)

**Comment by ngosang** [comment]
@BloodPriestess Sorry, we don't provide support for unofficial plugins.

You can try right click, save file as XXXXX.py and try to import in qBittorrent from file.

**Comment by Piccirello** [comment]
@BloodPriestess Can you walk me through the process you're using to import this plugin? URL import worked for me in the v4.1.5 GUI and v4.1.6 WebUI.
